export const athletes = {
  you: {
    id: "you",
    name: "You",
    handle: "@you.kairos",
    initials: "YO",
    homeGym: "Iron Peak Athletics",
    followers: 342,
    following: 198,
    streak: 12,
    sportBadges: [
      { label: "Running", emoji: "🏃" },
      { label: "Strength", emoji: "🏋️" },
    ],
    stats: { totalWorkouts: 214, prs: 9 },
    achievements: [
      { id: "a1", title: "First 10K", emoji: "🥇", detail: "Completed first 10K race", earned: true },
      { id: "a2", title: "30-Day Streak", emoji: "🔥", detail: "Trained 30 days in a row", earned: false },
      { id: "a3", title: "PR Machine", emoji: "💪", detail: "5 PRs in one month", earned: true },
      { id: "a4", title: "Challenge Champion", emoji: "🏆", detail: "Finished top 3 in a challenge", earned: false },
    ],
    challengeIds: ["c1"],
    posts: [
      {
        id: "you-1",
        type: "Run",
        time: "5h ago",
        title: "Easy shakeout before the long run",
        stats: [
          { label: "Distance", value: "6.4 km" },
          { label: "Pace", value: "5:30 /km" },
          { label: "Time", value: "35:12" },
        ],
        caption: "Keeping it light, saving the legs for Saturday.",
        likes: 41,
        comments: [{ id: "you-1-c1", user: "Maya", text: "Smart pacing 👏" }],
        liked: false,
      },
      {
        id: "you-2",
        type: "Strength",
        time: "2d ago",
        title: "Upper body — bench PR attempt",
        stats: [
          { label: "Lift", value: "Bench Press" },
          { label: "Max", value: "97.5 kg" },
          { label: "Sets", value: "4x2" },
        ],
        caption: "So close to the 100kg mark. Next week.",
        likes: 63,
        comments: [],
        liked: true,
      },
    ],
  },
  maya: {
    id: "maya",
    name: "Maya Kowalski",
    handle: "@maya.runs",
    initials: "MK",
    homeGym: "Riverside Run Club",
    followers: 1820,
    following: 340,
    streak: 28,
    sportBadges: [
      { label: "Running", emoji: "🏃" },
      { label: "Trail", emoji: "⛰️" },
    ],
    stats: { totalWorkouts: 512, prs: 14 },
    achievements: [
      { id: "a1", title: "First 10K", emoji: "🥇", detail: "Completed first 10K race", earned: true },
      { id: "a2", title: "30-Day Streak", emoji: "🔥", detail: "Trained 30 days in a row", earned: true },
      { id: "a3", title: "PR Machine", emoji: "💪", detail: "5 PRs in one month", earned: true },
      { id: "a4", title: "Challenge Champion", emoji: "🏆", detail: "Finished top 3 in a challenge", earned: false },
    ],
    challengeIds: ["c1", "c2"],
    posts: [
      {
        id: "maya-1",
        type: "Run",
        time: "22m ago",
        title: "Tempo run — new 10K PR",
        stats: [
          { label: "Distance", value: "10.2 km" },
          { label: "Pace", value: "4:12 /km" },
          { label: "Time", value: "42:51" },
        ],
        caption: "Chased that sub-43 for months. Legs are toast but worth it 🔥",
        likes: 128,
        comments: [
          { id: "cm1", user: "Deshawn", text: "LET'S GO. That pace is unreal." },
          { id: "cm2", user: "Coach Rex", text: "Splits looked perfectly even. Nice pacing." },
        ],
        liked: false,
      },
      {
        id: "maya-2",
        type: "Run",
        time: "3d ago",
        title: "Trail repeats — Vert Gains training",
        stats: [
          { label: "Distance", value: "14.8 km" },
          { label: "Elevation", value: "620 m" },
          { label: "Time", value: "1:28:40" },
        ],
        caption: "Hills don't get easier, you just get faster up them.",
        likes: 89,
        comments: [],
        liked: false,
      },
    ],
  },
  deshawn: {
    id: "deshawn",
    name: "Deshawn Walker",
    handle: "@dwalks_heavy",
    initials: "DW",
    homeGym: "Ironclad Barbell Club",
    followers: 960,
    following: 210,
    streak: 6,
    sportBadges: [
      { label: "Strength", emoji: "🏋️" },
      { label: "Powerlifting", emoji: "🏆" },
    ],
    stats: { totalWorkouts: 388, prs: 22 },
    achievements: [
      { id: "a1", title: "First 10K", emoji: "🥇", detail: "Completed first 10K race", earned: false },
      { id: "a2", title: "30-Day Streak", emoji: "🔥", detail: "Trained 30 days in a row", earned: false },
      { id: "a3", title: "PR Machine", emoji: "💪", detail: "5 PRs in one month", earned: true },
      { id: "a4", title: "Challenge Champion", emoji: "🏆", detail: "Finished top 3 in a challenge", earned: true },
    ],
    challengeIds: ["c3"],
    posts: [
      {
        id: "deshawn-1",
        type: "Strength",
        time: "1h ago",
        title: "Leg day — PR on back squat",
        stats: [
          { label: "Lift", value: "Back Squat" },
          { label: "Max", value: "182.5 kg" },
          { label: "Sets", value: "5x3" },
        ],
        caption: "Finally broke through the plateau. Onto 185 next week.",
        likes: 96,
        comments: [{ id: "cm3", user: "Maya", text: "Insane depth on that last rep" }],
        liked: true,
      },
      {
        id: "deshawn-2",
        type: "Strength",
        time: "4d ago",
        title: "Deadlift volume day — Iron Grip training",
        stats: [
          { label: "Lift", value: "Deadlift" },
          { label: "Volume", value: "4,920 kg" },
          { label: "Sets", value: "6x5" },
        ],
        caption: "Grip gave out before my back did. Chalk up next time.",
        likes: 71,
        comments: [],
        liked: false,
      },
    ],
  },
  priya: {
    id: "priya",
    name: "Priya Shah",
    handle: "@priya.climbs",
    initials: "PS",
    homeGym: "Summit Cycling Collective",
    followers: 1240,
    following: 275,
    streak: 15,
    sportBadges: [
      { label: "Cycling", emoji: "🚴" },
      { label: "Climbing", emoji: "⛰️" },
    ],
    stats: { totalWorkouts: 296, prs: 11 },
    achievements: [
      { id: "a1", title: "First 10K", emoji: "🥇", detail: "Completed first 10K race", earned: false },
      { id: "a2", title: "30-Day Streak", emoji: "🔥", detail: "Trained 30 days in a row", earned: false },
      { id: "a3", title: "PR Machine", emoji: "💪", detail: "5 PRs in one month", earned: false },
      { id: "a4", title: "Challenge Champion", emoji: "🏆", detail: "Finished top 3 in a challenge", earned: true },
    ],
    challengeIds: ["c4", "c1"],
    posts: [
      {
        id: "priya-1",
        type: "Ride",
        time: "3h ago",
        title: "Sunday long ride — Vert Gains challenge",
        stats: [
          { label: "Distance", value: "64.3 km" },
          { label: "Elevation", value: "1,140 m" },
          { label: "Avg Power", value: "212 W" },
        ],
        caption: "Climbed until my legs gave up. Vert Gains leaderboard, I'm coming for you.",
        likes: 74,
        comments: [],
        liked: false,
      },
      {
        id: "priya-2",
        type: "Ride",
        time: "6d ago",
        title: "Recovery spin",
        stats: [
          { label: "Distance", value: "28.0 km" },
          { label: "Elevation", value: "180 m" },
          { label: "Avg Power", value: "140 W" },
        ],
        caption: "Easy day. Legs said thank you.",
        likes: 38,
        comments: [{ id: "priya-2-c1", user: "Coach Rex", text: "Good discipline resting up." }],
        liked: false,
      },
    ],
  },
};

export function getAthlete(id) {
  return athletes[id];
}
