import { computeRunningAchievements, computeProgramAchievements } from "@/app/lib/achievements";

export const athletes = {
  you: {
    id: "you",
    name: "You",
    handle: "@you.kairos",
    initials: "YO",
    homeGym: "Iron Peak Athletics",
    followers: 342,
    following: 198,
    streak: 12,
    sportBadges: [
      { label: "Running", emoji: "🏃" },
      { label: "Strength", emoji: "🏋️" },
    ],
    stats: { totalWorkouts: 214 },
    runningStats: { totalRuns: 38, longestRunKm: 12, totalPRsBroken: 3, prsBrokenThisYear: 2, lifetimeMiles: 140 },
    programStats: {
      hyroxJoined: true,
      hyroxHighestLevel: 2,
      dekaLevels: { FIT: 1, MILE: 0, STRONG: 0, ATLAS: 0, DOUBLE: 0 },
      strengthLevels: { General: 2, Bodybuilding: 0, "Glute Focus": 0 },
      olyJoined: false,
      olyHighestLevel: 0,
      crossfitJoined: true,
      crossfitHighestLevel: 1,
      fireDeptJoined: false,
      fireDeptCycle: 0,
      lawEnforcementJoined: false,
      lawEnforcementCycle: 0,
    },
    achievements: [
      ...computeRunningAchievements({
        totalRuns: 38,
        longestRunKm: 12,
        totalPRsBroken: 3,
        lifetimeMiles: 140,
        mostRecentPR: { distance: "5K", time: "22:14" },
      }),
      ...computeProgramAchievements({
        hyroxJoined: true,
        hyroxHighestLevel: 2,
        dekaLevels: { FIT: 1, MILE: 0, STRONG: 0, ATLAS: 0, DOUBLE: 0 },
        strengthLevels: { General: 2, Bodybuilding: 0, "Glute Focus": 0 },
        olyJoined: false,
        olyHighestLevel: 0,
        crossfitJoined: true,
        crossfitHighestLevel: 1,
        fireDeptJoined: false,
        fireDeptCycle: 0,
        lawEnforcementJoined: false,
        lawEnforcementCycle: 0,
      }),
    ],
    // Every id here is a challenge where "You" is joined with progress 100 in mockData.js —
    // i.e. already hit the goal through the existing photo-proof submit flow — one from each
    // of the four consolidated distance sports plus HYROX's single-discipline 8K.
    challengeIds: ["wk-hyrox-8k", "wk-run-5", "wk-row-5", "wk-skierg-5", "wk-bike-10", "mo-bike-50"],
    completedChallengeIds: ["wk-hyrox-8k", "wk-run-5", "wk-row-5", "wk-skierg-5", "wk-bike-10", "mo-bike-50"],
    // Current consecutive-week streak per sport — see streaks.js. Spans all three tiers
    // (Running: past tier 1, Biking: past tier 2, SkiErg: past tier 3) plus one still building
    // toward its first tier (Rowing) for a good demo spread.
    streaks: { Running: 5, Biking: 9, Rowing: 2, SkiErg: 13 },
    posts: [
      {
        id: "you-1",
        type: "Run",
        time: "5h ago",
        title: "Easy shakeout before the long run",
        stats: [
          { label: "Distance", value: "6.4 km" },
          { label: "Pace", value: "5:30 /km" },
          { label: "Time", value: "35:12" },
        ],
        caption: "Keeping it light, saving the legs for Saturday.",
        likes: 41,
        comments: [{ id: "you-1-c1", user: "Maya", text: "Smart pacing 👏" }],
        liked: false,
      },
      {
        id: "you-2",
        type: "Strength",
        time: "2d ago",
        title: "Upper body — bench PR attempt",
        stats: [
          { label: "Lift", value: "Bench Press" },
          { label: "Max", value: "97.5 kg" },
          { label: "Sets", value: "4x2" },
        ],
        caption: "So close to the 100kg mark. Next week.",
        likes: 63,
        comments: [],
        liked: true,
      },
    ],
  },
  maya: {
    id: "maya",
    name: "Maya Kowalski",
    handle: "@maya.runs",
    initials: "MK",
    homeGym: "Riverside Run Club",
    followers: 1820,
    following: 340,
    streak: 28,
    sportBadges: [
      { label: "Running", emoji: "🏃" },
      { label: "Trail", emoji: "⛰️" },
    ],
    stats: { totalWorkouts: 512 },
    runningStats: { totalRuns: 210, longestRunKm: 42.5, totalPRsBroken: 14, prsBrokenThisYear: 5, lifetimeMiles: 1200 },
    programStats: {
      hyroxJoined: true,
      hyroxHighestLevel: 3,
      dekaLevels: { FIT: 3, MILE: 2, STRONG: 0, ATLAS: 0, DOUBLE: 0 },
      strengthLevels: { General: 0, Bodybuilding: 3, "Glute Focus": 1 },
      olyJoined: true,
      olyHighestLevel: 1,
      crossfitJoined: true,
      crossfitHighestLevel: 0,
      fireDeptJoined: true,
      fireDeptCycle: 2,
      lawEnforcementJoined: false,
      lawEnforcementCycle: 0,
    },
    achievements: [
      ...computeRunningAchievements({
        totalRuns: 210,
        longestRunKm: 42.5,
        totalPRsBroken: 14,
        lifetimeMiles: 1200,
        mostRecentPR: { distance: "Half Marathon", time: "1:28:10" },
      }),
      ...computeProgramAchievements({
        hyroxJoined: true,
        hyroxHighestLevel: 3,
        dekaLevels: { FIT: 3, MILE: 2, STRONG: 0, ATLAS: 0, DOUBLE: 0 },
        strengthLevels: { General: 0, Bodybuilding: 3, "Glute Focus": 1 },
        olyJoined: true,
        olyHighestLevel: 1,
        crossfitJoined: true,
        crossfitHighestLevel: 0,
        fireDeptJoined: true,
        fireDeptCycle: 2,
        lawEnforcementJoined: false,
        lawEnforcementCycle: 0,
      }),
    ],
    // Maya's cleared both Run 10 and Monthly 20 (completion badges); mo-row-50 she's active on
    // but hasn't hit the 50km goal yet (her score is 42km) — no completion badge for that one.
    challengeIds: ["wk-run-10", "mo-run-20", "mo-row-50"],
    completedChallengeIds: ["wk-run-10", "mo-run-20"],
    // Strong, long-running Running streak (past the 12-week top tier); a modest Rowing
    // streak just past its first tier; no Biking/SkiErg engagement.
    streaks: { Running: 12, Biking: 0, Rowing: 4, SkiErg: 0 },
    posts: [
      {
        id: "maya-1",
        type: "Run",
        time: "22m ago",
        title: "Tempo run — new 10K PR",
        stats: [
          { label: "Distance", value: "10.2 km" },
          { label: "Pace", value: "4:12 /km" },
          { label: "Time", value: "42:51" },
        ],
        caption: "Chased that sub-43 for months. Legs are toast but worth it 🔥",
        likes: 128,
        comments: [
          { id: "cm1", user: "Deshawn", text: "LET'S GO. That pace is unreal." },
          { id: "cm2", user: "Coach Rex", text: "Splits looked perfectly even. Nice pacing." },
        ],
        liked: false,
      },
      {
        id: "maya-2",
        type: "Run",
        time: "3d ago",
        title: "Trail repeats — Vert Gains training",
        stats: [
          { label: "Distance", value: "14.8 km" },
          { label: "Elevation", value: "620 m" },
          { label: "Time", value: "1:28:40" },
        ],
        caption: "Hills don't get easier, you just get faster up them.",
        likes: 89,
        comments: [],
        liked: false,
      },
    ],
  },
  deshawn: {
    id: "deshawn",
    name: "Deshawn Walker",
    handle: "@dwalks_heavy",
    initials: "DW",
    homeGym: "Ironclad Barbell Club",
    followers: 960,
    following: 210,
    streak: 6,
    sportBadges: [
      { label: "Strength", emoji: "🏋️" },
      { label: "Powerlifting", emoji: "🏆" },
    ],
    stats: { totalWorkouts: 388 },
    runningStats: { totalRuns: 0, longestRunKm: 0, totalPRsBroken: 0, prsBrokenThisYear: 0, lifetimeMiles: 0 },
    programStats: {
      hyroxJoined: false,
      hyroxHighestLevel: 0,
      dekaLevels: { FIT: 0, MILE: 0, STRONG: 0, ATLAS: 0, DOUBLE: 0 },
      strengthLevels: { General: 3, Bodybuilding: 2, "Glute Focus": 0 },
      olyJoined: true,
      olyHighestLevel: 3,
      crossfitJoined: true,
      crossfitHighestLevel: 2,
      fireDeptJoined: false,
      fireDeptCycle: 0,
      lawEnforcementJoined: true,
      lawEnforcementCycle: 3,
    },
    achievements: [
      ...computeRunningAchievements({ totalRuns: 0, longestRunKm: 0, totalPRsBroken: 0, lifetimeMiles: 0 }),
      ...computeProgramAchievements({
        hyroxJoined: false,
        hyroxHighestLevel: 0,
        dekaLevels: { FIT: 0, MILE: 0, STRONG: 0, ATLAS: 0, DOUBLE: 0 },
        strengthLevels: { General: 3, Bodybuilding: 2, "Glute Focus": 0 },
        olyJoined: true,
        olyHighestLevel: 3,
        crossfitJoined: true,
        crossfitHighestLevel: 2,
        fireDeptJoined: false,
        fireDeptCycle: 0,
        lawEnforcementJoined: true,
        lawEnforcementCycle: 3,
      }),
    ],
    // wk-hyrox-8k: Deshawn clears the 8,000m goal (9,400m) — completion badge earned.
    challengeIds: ["c3", "wk-hyrox-8k"],
    completedChallengeIds: ["wk-hyrox-8k"],
    // Deshawn is the broken/reset-streak demo: he was on a 6-week Running streak but missed
    // a week, so it's back to 0 across the board — a strength/HYROX athlete, not big on the
    // distance sports' weekly cadence.
    streaks: { Running: 0, Biking: 0, Rowing: 0, SkiErg: 0 },
    posts: [
      {
        id: "deshawn-1",
        type: "Strength",
        time: "1h ago",
        title: "Leg day — PR on back squat",
        stats: [
          { label: "Lift", value: "Back Squat" },
          { label: "Max", value: "182.5 kg" },
          { label: "Sets", value: "5x3" },
        ],
        caption: "Finally broke through the plateau. Onto 185 next week.",
        likes: 96,
        comments: [{ id: "cm3", user: "Maya", text: "Insane depth on that last rep" }],
        liked: true,
      },
      {
        id: "deshawn-2",
        type: "Strength",
        time: "4d ago",
        title: "Deadlift volume day — Iron Grip training",
        stats: [
          { label: "Lift", value: "Deadlift" },
          { label: "Volume", value: "4,920 kg" },
          { label: "Sets", value: "6x5" },
        ],
        caption: "Grip gave out before my back did. Chalk up next time.",
        likes: 71,
        comments: [],
        liked: false,
      },
    ],
  },
  priya: {
    id: "priya",
    name: "Priya Shah",
    handle: "@priya.climbs",
    initials: "PS",
    homeGym: "Summit Cycling Collective",
    followers: 1240,
    following: 275,
    streak: 15,
    sportBadges: [
      { label: "Cycling", emoji: "🚴" },
      { label: "Climbing", emoji: "⛰️" },
    ],
    stats: { totalWorkouts: 296 },
    runningStats: { totalRuns: 3, longestRunKm: 6, totalPRsBroken: 1, prsBrokenThisYear: 1, lifetimeMiles: 25 },
    programStats: {
      hyroxJoined: true,
      hyroxHighestLevel: 1,
      dekaLevels: { FIT: 0, MILE: 0, STRONG: 0, ATLAS: 2, DOUBLE: 0 },
      strengthLevels: { General: 0, Bodybuilding: 0, "Glute Focus": 0 },
      olyJoined: false,
      olyHighestLevel: 0,
      crossfitJoined: true,
      crossfitHighestLevel: 3,
      fireDeptJoined: true,
      fireDeptCycle: 1,
      lawEnforcementJoined: true,
      lawEnforcementCycle: 2,
    },
    achievements: [
      ...computeRunningAchievements({
        totalRuns: 3,
        longestRunKm: 6,
        totalPRsBroken: 1,
        lifetimeMiles: 25,
        mostRecentPR: { distance: "10K", time: "58:32" },
      }),
      ...computeProgramAchievements({
        hyroxJoined: true,
        hyroxHighestLevel: 1,
        dekaLevels: { FIT: 0, MILE: 0, STRONG: 0, ATLAS: 2, DOUBLE: 0 },
        strengthLevels: { General: 0, Bodybuilding: 0, "Glute Focus": 0 },
        olyJoined: false,
        olyHighestLevel: 0,
        crossfitJoined: true,
        crossfitHighestLevel: 3,
        fireDeptJoined: true,
        fireDeptCycle: 1,
        lawEnforcementJoined: true,
        lawEnforcementCycle: 2,
      }),
    ],
    // Priya's cleared Bike 10K and Bike 50K Monthly (completion badges); she's active on
    // Bike 25K and Bike 100K but hasn't hit those goals yet (21km of 25km, 82km of 100km).
    challengeIds: ["wk-bike-10", "wk-bike-25", "mo-bike-50", "mo-bike-100"],
    completedChallengeIds: ["wk-bike-10", "mo-bike-50"],
    // Solid Biking streak past its 8-week tier; a SkiErg streak just getting started (below
    // the first tier); no Running/Rowing engagement.
    streaks: { Running: 0, Biking: 8, Rowing: 0, SkiErg: 3 },
    posts: [
      {
        id: "priya-1",
        type: "Ride",
        time: "3h ago",
        title: "Sunday long ride — Vert Gains challenge",
        stats: [
          { label: "Distance", value: "64.3 km" },
          { label: "Elevation", value: "1,140 m" },
          { label: "Avg Power", value: "212 W" },
        ],
        caption: "Climbed until my legs gave up. Vert Gains leaderboard, I'm coming for you.",
        likes: 74,
        comments: [],
        liked: false,
      },
      {
        id: "priya-2",
        type: "Ride",
        time: "6d ago",
        title: "Recovery spin",
        stats: [
          { label: "Distance", value: "28.0 km" },
          { label: "Elevation", value: "180 m" },
          { label: "Avg Power", value: "140 W" },
        ],
        caption: "Easy day. Legs said thank you.",
        likes: 38,
        comments: [{ id: "priya-2-c1", user: "Coach Rex", text: "Good discipline resting up." }],
        liked: false,
      },
    ],
  },
};

export function getAthlete(id) {
  return athletes[id];
}
