export const stories = [
  { id: "you", name: "Your Story", initials: "YO", isSelf: true, viewed: false },
  { id: "u1", name: "Maya K.", initials: "MK", viewed: false },
  { id: "u2", name: "Deshawn", initials: "DW", viewed: false },
  { id: "u3", name: "Elena", initials: "EL", viewed: true },
  { id: "u4", name: "Priya", initials: "PS", viewed: false },
  { id: "u5", name: "Coach Rex", initials: "CR", viewed: false },
  { id: "u6", name: "Jonas", initials: "JB", viewed: true },
  { id: "u7", name: "Wren", initials: "WT", viewed: true },
];

export const sponsoredAd = {
  brand: "SurgeFuel",
  tagline: "Electrolytes built for race day. 0 sugar, all send.",
  cta: "Shop Now",
  badge: "SF",
};

// Every challenge belongs to exactly one activity category — CHALLENGE_CATEGORIES below is
// the canonical ordered list the Challenges tab groups by. Running is fully populated;
// everything else has at least one example so the category/accordion structure and
// navigation can be verified end-to-end even before those lists are fleshed out for real.
export const CHALLENGE_CATEGORIES = [
  "Running",
  "Biking",
  "SkiErg",
  "Rowing",
  "Olympic Weightlifting",
  "HYROX",
  "DEKA",
  "Strength & Conditioning",
  "Public Safety Prep",
];

export const challenges = [
  {
    id: "c3",
    title: "Iron Grip",
    sub: "Strength & Conditioning · Ends in 5 days",
    category: "Strength & Conditioning",
    goal: "Max deadlift volume",
    duration: "2 Weeks",
    description:
      "Total deadlift volume challenge. Log your heaviest working sets — weight × reps determines your total volume and your rank on the board.",
    startDate: "Jul 29, 2026",
    endDate: "Aug 14, 2026",
    prize: "Iron Grip Chalk Bag + Leaderboard Feature",
    participants: 976,
    progress: 88,
    joined: false,
    unit: "kg vol",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "c3-1", name: "Deshawn Walker", initials: "DW", score: 14820 },
      { id: "c3-2", name: "Marcus Lee", initials: "ML", score: 13990 },
      { id: "c3-3", name: "Elena Cruz", initials: "EC", score: 11200 },
      { id: "c3-4", name: "Priya Shah", initials: "PS", score: 9840 },
    ],
  },
  // Weekly Running mileage challenges — 1-week window, progress tracked toward each
  // challenge's mile goal the same way every other challenge tracks its own unit.
  {
    id: "wk-run-5",
    title: "Run 5",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "5 miles",
    duration: "1 Week",
    description: "Log 5 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 5 Badge",
    participants: 2140,
    progress: 100,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wk5-1", name: "Elena Cruz", initials: "EC", score: 5.8 },
      { id: "wk5-2", name: "You", initials: "YO", score: 5.0, isSelf: true },
      { id: "wk5-3", name: "Jonas B.", initials: "JB", score: 4.6 },
    ],
  },
  {
    id: "wk-run-10",
    title: "Run 10",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "10 miles",
    duration: "1 Week",
    description: "Log 10 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 10 Badge",
    participants: 1875,
    progress: 100,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wk10-1", name: "Maya Kowalski", initials: "MK", score: 14.2 },
      { id: "wk10-2", name: "You", initials: "YO", score: 10.0, isSelf: true },
      { id: "wk10-3", name: "Wren Torres", initials: "WT", score: 9.1 },
    ],
  },
  {
    id: "wk-run-15",
    title: "Run 15",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "15 miles",
    duration: "1 Week",
    description: "Log 15 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 15 Badge",
    participants: 1402,
    progress: 60,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wk15-1", name: "Maya Kowalski", initials: "MK", score: 13.5 },
      { id: "wk15-2", name: "You", initials: "YO", score: 9.0, isSelf: true },
      { id: "wk15-3", name: "Coach Rex", initials: "CR", score: 6.2 },
    ],
  },
  {
    id: "wk-run-20",
    title: "Run 20",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "20 miles",
    duration: "1 Week",
    description: "Log 20 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 20 Badge",
    participants: 968,
    progress: 40,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wk20-1", name: "Maya Kowalski", initials: "MK", score: 17.0 },
      { id: "wk20-2", name: "You", initials: "YO", score: 8.0, isSelf: true },
      { id: "wk20-3", name: "Priya Shah", initials: "PS", score: 5.4 },
    ],
  },
  {
    id: "wk-run-30",
    title: "Run 30",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "30 miles",
    duration: "1 Week",
    description: "Log 30 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 30 Badge",
    participants: 511,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wk30-1", name: "Maya Kowalski", initials: "MK", score: 22.4 },
      { id: "wk30-2", name: "Elena Cruz", initials: "EC", score: 18.9 },
    ],
  },
  {
    id: "wk-run-40",
    title: "Run 40",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "40 miles",
    duration: "1 Week",
    description: "Log 40 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 40 Badge",
    participants: 284,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wk40-1", name: "Maya Kowalski", initials: "MK", score: 28.1 },
      { id: "wk40-2", name: "Marcus Lee", initials: "ML", score: 19.6 },
    ],
  },
  {
    id: "wk-run-50",
    title: "Run 50",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "50 miles",
    duration: "1 Week",
    description: "Log 50 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 50 Badge",
    participants: 132,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "wk50-1", name: "Maya Kowalski", initials: "MK", score: 31.7 }],
  },
  {
    id: "wk-run-60",
    title: "Run 60",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "60 miles",
    duration: "1 Week",
    description: "Log 60 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 60 Badge",
    participants: 47,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "wk60-1", name: "Maya Kowalski", initials: "MK", score: 34.0 }],
  },
  // Monthly Running mileage challenges — 1-month window, same progress-tracking pattern.
  {
    id: "mo-run-10",
    title: "Monthly 10",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "10 miles",
    duration: "1 Month",
    description: "Log 10 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Monthly 10 Badge",
    participants: 2984,
    progress: 100,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "mo10-1", name: "Elena Cruz", initials: "EC", score: 24.8 },
      { id: "mo10-2", name: "You", initials: "YO", score: 10.0, isSelf: true },
      { id: "mo10-3", name: "Jonas B.", initials: "JB", score: 9.2 },
    ],
  },
  {
    id: "mo-run-20",
    title: "Monthly 20",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "20 miles",
    duration: "1 Month",
    description: "Log 20 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Monthly 20 Badge",
    participants: 2317,
    progress: 100,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "mo20-1", name: "Maya Kowalski", initials: "MK", score: 46.5 },
      { id: "mo20-2", name: "You", initials: "YO", score: 20.0, isSelf: true },
      { id: "mo20-3", name: "Wren Torres", initials: "WT", score: 18.3 },
    ],
  },
  {
    id: "mo-run-30",
    title: "Monthly 30",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "30 miles",
    duration: "1 Month",
    description: "Log 30 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Monthly 30 Badge",
    participants: 1690,
    progress: 70,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "mo30-1", name: "Maya Kowalski", initials: "MK", score: 52.0 },
      { id: "mo30-2", name: "You", initials: "YO", score: 21.0, isSelf: true },
      { id: "mo30-3", name: "Coach Rex", initials: "CR", score: 17.4 },
    ],
  },
  {
    id: "mo-run-40",
    title: "Monthly 40",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "40 miles",
    duration: "1 Month",
    description: "Log 40 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Monthly 40 Badge",
    participants: 1104,
    progress: 45,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "mo40-1", name: "Maya Kowalski", initials: "MK", score: 61.8 },
      { id: "mo40-2", name: "You", initials: "YO", score: 18.0, isSelf: true },
      { id: "mo40-3", name: "Priya Shah", initials: "PS", score: 12.5 },
    ],
  },
  {
    id: "mo-run-50",
    title: "Monthly 50",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "50 miles",
    duration: "1 Month",
    description: "Log 50 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Monthly 50 Badge",
    participants: 742,
    progress: 20,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "mo50-1", name: "Maya Kowalski", initials: "MK", score: 68.4 },
      { id: "mo50-2", name: "Elena Cruz", initials: "EC", score: 33.1 },
      { id: "mo50-3", name: "You", initials: "YO", score: 10.0, isSelf: true },
    ],
  },
  {
    id: "mo-run-60",
    title: "Monthly 60",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "60 miles",
    duration: "1 Month",
    description: "Log 60 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Monthly 60 Badge",
    participants: 398,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "mo60-1", name: "Maya Kowalski", initials: "MK", score: 74.2 },
      { id: "mo60-2", name: "Marcus Lee", initials: "ML", score: 41.0 },
    ],
  },
  {
    id: "mo-run-75",
    title: "Monthly 75",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "75 miles",
    duration: "1 Month",
    description: "Log 75 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Monthly 75 Badge",
    participants: 215,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "mo75-1", name: "Maya Kowalski", initials: "MK", score: 81.6 }],
  },
  {
    id: "mo-century-run",
    title: "Century Run",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "100 miles",
    duration: "1 Month",
    description: "Log 100 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Century Badge",
    participants: 109,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "mocent-1", name: "Maya Kowalski", initials: "MK", score: 94.3 }],
  },
  {
    id: "mo-run-150",
    title: "Run 150",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "150 miles",
    duration: "1 Month",
    description: "Log 150 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Run 150 Badge",
    participants: 38,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "mo150-1", name: "Maya Kowalski", initials: "MK", score: 112.0 }],
  },
  {
    id: "mo-run-200",
    title: "Run 200",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "200 miles",
    duration: "1 Month",
    description: "Log 200 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Run 200 Badge",
    participants: 14,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "mo200-1", name: "Maya Kowalski", initials: "MK", score: 121.5 }],
  },
  // Weekly Rowing distance challenges — same progress-tracking pattern as Running, kilometers instead of miles.
  {
    id: "wk-row-5",
    title: "Row 5K",
    sub: "Rowing · Ends in 6 days",
    category: "Rowing",
    goal: "5 kilometers",
    duration: "1 Week",
    description: "Row 5 kilometers within one week to complete this challenge. Erg or water — every tracked kilometer counts.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Row 5K Badge",
    participants: 340,
    progress: 100,
    joined: true,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wkrow5-1", name: "Elena Cruz", initials: "EC", score: 5.8 },
      { id: "wkrow5-2", name: "You", initials: "YO", score: 5.0, isSelf: true },
      { id: "wkrow5-3", name: "Jonas B.", initials: "JB", score: 4.6 },
    ],
  },
  {
    id: "wk-row-10",
    title: "Row 10K",
    sub: "Rowing · Ends in 6 days",
    category: "Rowing",
    goal: "10 kilometers",
    duration: "1 Week",
    description: "Row 10 kilometers within one week to complete this challenge. Erg or water — every tracked kilometer counts.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Row 10K Badge",
    participants: 210,
    progress: 65,
    joined: true,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wkrow10-1", name: "Wren Torres", initials: "WT", score: 8.9 },
      { id: "wkrow10-2", name: "You", initials: "YO", score: 6.5, isSelf: true },
      { id: "wkrow10-3", name: "Coach Rex", initials: "CR", score: 4.1 },
    ],
  },
  {
    id: "wk-row-20",
    title: "Row 20K",
    sub: "Rowing · Ends in 6 days",
    category: "Rowing",
    goal: "20 kilometers",
    duration: "1 Week",
    description: "Row 20 kilometers within one week to complete this challenge. Erg or water — every tracked kilometer counts.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Row 20K Badge",
    participants: 95,
    progress: 0,
    joined: false,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wkrow20-1", name: "Maya Kowalski", initials: "MK", score: 17.0 },
      { id: "wkrow20-2", name: "Elena Cruz", initials: "EC", score: 12.3 },
    ],
  },
  {
    id: "wk-row-25",
    title: "Row 25K",
    sub: "Rowing · Ends in 6 days",
    category: "Rowing",
    goal: "25 kilometers",
    duration: "1 Week",
    description: "Row 25 kilometers within one week to complete this challenge. Erg or water — every tracked kilometer counts.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Row 25K Badge",
    participants: 61,
    progress: 0,
    joined: false,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wkrow25-1", name: "Maya Kowalski", initials: "MK", score: 21.0 },
      { id: "wkrow25-2", name: "Elena Cruz", initials: "EC", score: 15.8 },
    ],
  },
  // Monthly Rowing distance challenges — 1-month window, same progress-tracking pattern.
  {
    id: "mo-row-25",
    title: "Row 25K Monthly",
    sub: "Rowing · Ends in 7 days",
    category: "Rowing",
    goal: "25 kilometers",
    duration: "1 Month",
    description: "Row 25 kilometers within the month to complete this challenge. Erg or water — every tracked kilometer counts.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Row 25K Monthly Badge",
    participants: 260,
    progress: 100,
    joined: true,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "morow25-1", name: "Elena Cruz", initials: "EC", score: 31.0 },
      { id: "morow25-2", name: "You", initials: "YO", score: 25.0, isSelf: true },
      { id: "morow25-3", name: "Priya Shah", initials: "PS", score: 21.0 },
    ],
  },
  {
    id: "mo-row-50",
    title: "Row 50K",
    sub: "Rowing · Ends in 7 days",
    category: "Rowing",
    goal: "50 kilometers",
    duration: "1 Month",
    description: "Row 50 kilometers within the month to complete this challenge. Erg or water — every tracked kilometer counts.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Row 50K Badge",
    participants: 140,
    progress: 40,
    joined: true,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "morow50-1", name: "Maya Kowalski", initials: "MK", score: 42.0 },
      { id: "morow50-2", name: "You", initials: "YO", score: 20.0, isSelf: true },
      { id: "morow50-3", name: "Marcus Lee", initials: "ML", score: 15.5 },
    ],
  },
  {
    id: "mo-row-75",
    title: "Row 75K",
    sub: "Rowing · Ends in 7 days",
    category: "Rowing",
    goal: "75 kilometers",
    duration: "1 Month",
    description: "Row 75 kilometers within the month to complete this challenge. Erg or water — every tracked kilometer counts.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Row 75K Badge",
    participants: 78,
    progress: 0,
    joined: false,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "morow75-1", name: "Maya Kowalski", initials: "MK", score: 54.0 }],
  },
  {
    id: "mo-row-100",
    title: "Row 100K",
    sub: "Rowing · Ends in 7 days",
    category: "Rowing",
    goal: "100 kilometers",
    duration: "1 Month",
    description: "Row 100 kilometers within the month to complete this challenge. Erg or water — every tracked kilometer counts.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Row 100K Badge",
    participants: 52,
    progress: 0,
    joined: false,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "morow100-1", name: "Maya Kowalski", initials: "MK", score: 68.0 }],
  },
  // Weekly SkiErg distance challenges — same progress-tracking pattern as Running, kilometers instead of miles.
  {
    id: "wk-skierg-5",
    title: "SkiErg 5K",
    sub: "SkiErg · Ends in 6 days",
    category: "SkiErg",
    goal: "5 kilometers",
    duration: "1 Week",
    description: "SkiErg 5 kilometers within one week to complete this challenge. Every tracked kilometer counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos SkiErg 5K Badge",
    participants: 98,
    progress: 100,
    joined: true,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wkskierg5-1", name: "Coach Rex", initials: "CR", score: 5.6 },
      { id: "wkskierg5-2", name: "You", initials: "YO", score: 5.0, isSelf: true },
      { id: "wkskierg5-3", name: "Wren Torres", initials: "WT", score: 4.3 },
    ],
  },
  {
    id: "wk-skierg-10",
    title: "SkiErg 10K",
    sub: "SkiErg · Ends in 6 days",
    category: "SkiErg",
    goal: "10 kilometers",
    duration: "1 Week",
    description: "SkiErg 10 kilometers within one week to complete this challenge. Every tracked kilometer counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos SkiErg 10K Badge",
    participants: 61,
    progress: 55,
    joined: true,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wkskierg10-1", name: "Deshawn Walker", initials: "DW", score: 8.7 },
      { id: "wkskierg10-2", name: "You", initials: "YO", score: 5.5, isSelf: true },
    ],
  },
  {
    id: "wk-skierg-20",
    title: "SkiErg 20K",
    sub: "SkiErg · Ends in 6 days",
    category: "SkiErg",
    goal: "20 kilometers",
    duration: "1 Week",
    description: "SkiErg 20 kilometers within one week to complete this challenge. Every tracked kilometer counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos SkiErg 20K Badge",
    participants: 27,
    progress: 0,
    joined: false,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "wkskierg20-1", name: "Coach Rex", initials: "CR", score: 14.2 }],
  },
  {
    id: "wk-skierg-25",
    title: "SkiErg 25K",
    sub: "SkiErg · Ends in 6 days",
    category: "SkiErg",
    goal: "25 kilometers",
    duration: "1 Week",
    description: "SkiErg 25 kilometers within one week to complete this challenge. Every tracked kilometer counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos SkiErg 25K Badge",
    participants: 18,
    progress: 0,
    joined: false,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "wkskierg25-1", name: "Coach Rex", initials: "CR", score: 19.5 }],
  },
  // Monthly SkiErg distance challenges — 1-month window, same progress-tracking pattern.
  {
    id: "mo-skierg-25",
    title: "SkiErg 25K Monthly",
    sub: "SkiErg · Ends in 7 days",
    category: "SkiErg",
    goal: "25 kilometers",
    duration: "1 Month",
    description: "SkiErg 25 kilometers within the month to complete this challenge. Every tracked kilometer counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos SkiErg 25K Monthly Badge",
    participants: 74,
    progress: 100,
    joined: true,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "moskierg25-1", name: "Coach Rex", initials: "CR", score: 29.5 },
      { id: "moskierg25-2", name: "You", initials: "YO", score: 25.0, isSelf: true },
      { id: "moskierg25-3", name: "Wren Torres", initials: "WT", score: 19.8 },
    ],
  },
  {
    id: "mo-skierg-50",
    title: "SkiErg 50K",
    sub: "SkiErg · Ends in 7 days",
    category: "SkiErg",
    goal: "50 kilometers",
    duration: "1 Month",
    description: "SkiErg 50 kilometers within the month to complete this challenge. Every tracked kilometer counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos SkiErg 50K Badge",
    participants: 39,
    progress: 35,
    joined: true,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "moskierg50-1", name: "Coach Rex", initials: "CR", score: 38.0 },
      { id: "moskierg50-2", name: "You", initials: "YO", score: 17.5, isSelf: true },
    ],
  },
  {
    id: "mo-skierg-75",
    title: "SkiErg 75K",
    sub: "SkiErg · Ends in 7 days",
    category: "SkiErg",
    goal: "75 kilometers",
    duration: "1 Month",
    description: "SkiErg 75 kilometers within the month to complete this challenge. Every tracked kilometer counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos SkiErg 75K Badge",
    participants: 24,
    progress: 0,
    joined: false,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "moskierg75-1", name: "Coach Rex", initials: "CR", score: 46.0 }],
  },
  {
    id: "mo-skierg-100",
    title: "SkiErg 100K",
    sub: "SkiErg · Ends in 7 days",
    category: "SkiErg",
    goal: "100 kilometers",
    duration: "1 Month",
    description: "SkiErg 100 kilometers within the month to complete this challenge. Every tracked kilometer counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos SkiErg 100K Badge",
    participants: 16,
    progress: 0,
    joined: false,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "moskierg100-1", name: "Coach Rex", initials: "CR", score: 61.0 }],
  },
  // Weekly Biking distance challenges — same progress-tracking pattern as Running, kilometers instead of miles.
  {
    id: "wk-bike-10",
    title: "Bike 10K",
    sub: "Biking · Ends in 6 days",
    category: "Biking",
    goal: "10 kilometers",
    duration: "1 Week",
    description: "Bike 10 kilometers within one week to complete this challenge. Every tracked ride counts toward your total distance.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Bike 10K Badge",
    participants: 410,
    progress: 100,
    joined: true,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wkbike10-1", name: "Priya Shah", initials: "PS", score: 12.4 },
      { id: "wkbike10-2", name: "You", initials: "YO", score: 10.0, isSelf: true },
      { id: "wkbike10-3", name: "Jonas B.", initials: "JB", score: 8.6 },
    ],
  },
  {
    id: "wk-bike-25",
    title: "Bike 25K",
    sub: "Biking · Ends in 6 days",
    category: "Biking",
    goal: "25 kilometers",
    duration: "1 Week",
    description: "Bike 25 kilometers within one week to complete this challenge. Every tracked ride counts toward your total distance.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Bike 25K Badge",
    participants: 265,
    progress: 70,
    joined: true,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wkbike25-1", name: "Priya Shah", initials: "PS", score: 21.0 },
      { id: "wkbike25-2", name: "You", initials: "YO", score: 17.5, isSelf: true },
    ],
  },
  {
    id: "wk-bike-50",
    title: "Bike 50K",
    sub: "Biking · Ends in 6 days",
    category: "Biking",
    goal: "50 kilometers",
    duration: "1 Week",
    description: "Bike 50 kilometers within one week to complete this challenge. Every tracked ride counts toward your total distance.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Bike 50K Badge",
    participants: 120,
    progress: 0,
    joined: false,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "wkbike50-1", name: "Priya Shah", initials: "PS", score: 38.0 }],
  },
  // Monthly Biking distance challenges — 1-month window, same progress-tracking pattern.
  // Bike 50K Monthly here is a separate challenge from the weekly Bike 50K above (same
  // distance, different period) — titled distinctly to match the Rowing/SkiErg convention
  // (Row 25K / Row 25K Monthly, SkiErg 25K / SkiErg 25K Monthly) instead of reusing the
  // identical "Bike 50K" title for both, avoiding a naming collision between the two cards.
  {
    id: "mo-bike-50",
    title: "Bike 50K Monthly",
    sub: "Biking · Ends in 7 days",
    category: "Biking",
    goal: "50 kilometers",
    duration: "1 Month",
    description: "Bike 50 kilometers within the month to complete this challenge. Every tracked ride counts toward your total distance.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Bike 50K Monthly Badge",
    participants: 305,
    progress: 100,
    joined: true,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "mobike50-1", name: "Priya Shah", initials: "PS", score: 64.0 },
      { id: "mobike50-2", name: "You", initials: "YO", score: 50.0, isSelf: true },
      { id: "mobike50-3", name: "Coach Rex", initials: "CR", score: 42.0 },
    ],
  },
  {
    id: "mo-bike-100",
    title: "Bike 100K",
    sub: "Biking · Ends in 7 days",
    category: "Biking",
    goal: "100 kilometers",
    duration: "1 Month",
    description: "Bike 100 kilometers within the month to complete this challenge. Every tracked ride counts toward your total distance.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Bike 100K Badge",
    participants: 168,
    progress: 30,
    joined: true,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "mobike100-1", name: "Priya Shah", initials: "PS", score: 82.0 },
      { id: "mobike100-2", name: "You", initials: "YO", score: 30.0, isSelf: true },
    ],
  },
  {
    id: "mo-bike-200",
    title: "Bike 200K",
    sub: "Biking · Ends in 7 days",
    category: "Biking",
    goal: "200 kilometers",
    duration: "1 Month",
    description: "Bike 200 kilometers within the month to complete this challenge. Every tracked ride counts toward your total distance.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Bike 200K Badge",
    participants: 58,
    progress: 0,
    joined: false,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "mobike200-1", name: "Priya Shah", initials: "PS", score: 124.0 }],
  },
  // HYROX challenges — single-discipline only, same flat-progress pattern as
  // Running/Rowing/SkiErg/Biking. The multi-component combo challenges (HYROX Engine, HYROX
  // Double, HYROX 25K/50K, Engine Month) were removed in the Challenges consolidation —
  // out of scope for now, individual single-distance challenges only. The `components`
  // array field ({ label, unit, current, goal }) and its rendering in ChallengeDetail.js /
  // ChallengesScreen.js are left in place (no remaining challenge sets it) in case
  // multi-part challenges come back later.
  {
    id: "wk-hyrox-8k",
    title: "HYROX 8K",
    sub: "HYROX · Ends in 6 days",
    category: "HYROX",
    goal: "8,000 meters running",
    duration: "1 Week",
    description: "Accumulate 8,000 meters of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos HYROX 8K Badge",
    participants: 210,
    progress: 100,
    joined: true,
    unit: "m",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wkhyrox8k-1", name: "Deshawn Walker", initials: "DW", score: 9400 },
      { id: "wkhyrox8k-2", name: "You", initials: "YO", score: 8000, isSelf: true },
      { id: "wkhyrox8k-3", name: "Priya Shah", initials: "PS", score: 7100 },
    ],
  },
  {
    id: "wk-hyrox-ski",
    title: "HYROX Ski",
    sub: "HYROX · Ends in 6 days",
    category: "HYROX",
    goal: "5,000 meters SkiErg",
    duration: "1 Week",
    description: "Accumulate 5,000 meters on the SkiErg within one week to complete this challenge. Every tracked erg session counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos HYROX Ski Badge",
    participants: 130,
    progress: 60,
    joined: true,
    unit: "m",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wkhyroxski-1", name: "Wren Torres", initials: "WT", score: 4400 },
      { id: "wkhyroxski-2", name: "You", initials: "YO", score: 3000, isSelf: true },
    ],
  },
  {
    id: "wk-hyrox-row",
    title: "HYROX Row",
    sub: "HYROX · Ends in 6 days",
    category: "HYROX",
    goal: "5,000 meters rowing",
    duration: "1 Week",
    description: "Accumulate 5,000 meters of rowing within one week to complete this challenge. Every tracked erg session counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos HYROX Row Badge",
    participants: 95,
    progress: 0,
    joined: false,
    unit: "m",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "wkhyroxrow-1", name: "Coach Rex", initials: "CR", score: 4100 }],
  },
  // Placeholder examples for the remaining categories — enough to prove the accordion/detail
  // structure and navigation work end-to-end; full lists for these can come later.
  {
    id: "oly-new-snatch-pr",
    title: "New Snatch PR",
    sub: "Olympic Weightlifting · Ends in 7 days",
    category: "Olympic Weightlifting",
    goal: "Set a new snatch PR",
    duration: "1 Month",
    description: "Set a new personal record on the snatch this month. Submit your best make with a video or photo of the lift.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Snatch PR Badge",
    participants: 41,
    progress: 0,
    joined: false,
    unit: "kg",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "oly-1", name: "Marcus Lee", initials: "ML", score: 92 }],
  },
  {
    id: "hyrox-simulation",
    title: "HYROX Simulation",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "Complete a full HYROX simulation",
    duration: "1 Month",
    description: "Complete a full HYROX simulation — all 8 stations and runs, at race pace — sometime this month.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos HYROX Simulation Badge",
    participants: 76,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "hyrox-c-1", name: "Deshawn Walker", initials: "DW", score: 1 }],
  },
  // HYROX combo challenges — mixed-movement workouts at fixed distances, each completed in
  // one session back to back (not accumulated over the week/month like the single-discipline
  // HYROX challenges above). `components` breaks down the per-movement distance the same way
  // ChallengeDetail.js's "By Discipline" panel already renders it for any challenge that sets
  // the field. The six 2-movement combos each ship two distance variations (A leans shorter on
  // the first movement, B leans shorter on the second) per the HYROX combo spec.
  {
    id: "hyrox-combo-ski-row-a",
    title: "Ski + Row (A)",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "500m Ski + 500m Row",
    duration: "1 Month",
    description: "Complete this HYROX combo — 500m Ski erg followed immediately by 500m row — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Ski + Row (A) Badge",
    participants: 24,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Ski", current: 0, goal: 500, unit: "m" },
      { label: "Row", current: 0, goal: 500, unit: "m" },
    ],
    leaderboard: [{ id: "hcsra-1", name: "Deshawn Walker", initials: "DW", score: 1 }],
  },
  {
    id: "hyrox-combo-ski-row-b",
    title: "Ski + Row (B)",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "250m Ski + 750m Row",
    duration: "1 Month",
    description: "Complete this HYROX combo — 250m Ski erg followed immediately by 750m row — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Ski + Row (B) Badge",
    participants: 19,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Ski", current: 0, goal: 250, unit: "m" },
      { label: "Row", current: 0, goal: 750, unit: "m" },
    ],
    leaderboard: [{ id: "hcsrb-1", name: "Maya Kowalski", initials: "MK", score: 1 }],
  },
  {
    id: "hyrox-combo-ski-bike-a",
    title: "Ski + Bike (A)",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "500m Ski + 2K Bike",
    duration: "1 Month",
    description: "Complete this HYROX combo — 500m Ski erg followed immediately by a 2K bike — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Ski + Bike (A) Badge",
    participants: 22,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Ski", current: 0, goal: 500, unit: "m" },
      { label: "Bike", current: 0, goal: 2000, unit: "m" },
    ],
    leaderboard: [{ id: "hcsba-1", name: "Priya Shah", initials: "PS", score: 1 }],
  },
  {
    id: "hyrox-combo-ski-bike-b",
    title: "Ski + Bike (B)",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "250m Ski + 3K Bike",
    duration: "1 Month",
    description: "Complete this HYROX combo — 250m Ski erg followed immediately by a 3K bike — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Ski + Bike (B) Badge",
    participants: 17,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Ski", current: 0, goal: 250, unit: "m" },
      { label: "Bike", current: 0, goal: 3000, unit: "m" },
    ],
    leaderboard: [{ id: "hcsbb-1", name: "Wren Torres", initials: "WT", score: 1 }],
  },
  {
    id: "hyrox-combo-ski-run-a",
    title: "Ski + Run (A)",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "500m Ski + 1K Run",
    duration: "1 Month",
    description: "Complete this HYROX combo — 500m Ski erg followed immediately by a 1K run — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Ski + Run (A) Badge",
    participants: 28,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Ski", current: 0, goal: 500, unit: "m" },
      { label: "Run", current: 0, goal: 1000, unit: "m" },
    ],
    leaderboard: [{ id: "hcska-1", name: "Coach Rex", initials: "CR", score: 1 }],
  },
  {
    id: "hyrox-combo-ski-run-b",
    title: "Ski + Run (B)",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "250m Ski + 500m Run",
    duration: "1 Month",
    description: "Complete this HYROX combo — 250m Ski erg followed immediately by a 500m run — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Ski + Run (B) Badge",
    participants: 21,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Ski", current: 0, goal: 250, unit: "m" },
      { label: "Run", current: 0, goal: 500, unit: "m" },
    ],
    leaderboard: [{ id: "hcskb-1", name: "Elena Cruz", initials: "EC", score: 1 }],
  },
  {
    id: "hyrox-combo-row-bike-a",
    title: "Row + Bike (A)",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "750m Row + 3K Bike",
    duration: "1 Month",
    description: "Complete this HYROX combo — 750m row followed immediately by a 3K bike — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Row + Bike (A) Badge",
    participants: 20,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Row", current: 0, goal: 750, unit: "m" },
      { label: "Bike", current: 0, goal: 3000, unit: "m" },
    ],
    leaderboard: [{ id: "hcrba-1", name: "Marcus Lee", initials: "ML", score: 1 }],
  },
  {
    id: "hyrox-combo-row-bike-b",
    title: "Row + Bike (B)",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "500m Row + 2K Bike",
    duration: "1 Month",
    description: "Complete this HYROX combo — 500m row followed immediately by a 2K bike — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Row + Bike (B) Badge",
    participants: 18,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Row", current: 0, goal: 500, unit: "m" },
      { label: "Bike", current: 0, goal: 2000, unit: "m" },
    ],
    leaderboard: [{ id: "hcrbb-1", name: "Jonas Bauer", initials: "JB", score: 1 }],
  },
  {
    id: "hyrox-combo-row-run-a",
    title: "Row + Run (A)",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "1K Row + 1K Run",
    duration: "1 Month",
    description: "Complete this HYROX combo — a 1K row followed immediately by a 1K run — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Row + Run (A) Badge",
    participants: 26,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Row", current: 0, goal: 1000, unit: "m" },
      { label: "Run", current: 0, goal: 1000, unit: "m" },
    ],
    leaderboard: [{ id: "hcrra-1", name: "Deshawn Walker", initials: "DW", score: 1 }],
  },
  {
    id: "hyrox-combo-row-run-b",
    title: "Row + Run (B)",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "500m Row + 500m Run",
    duration: "1 Month",
    description: "Complete this HYROX combo — 500m row followed immediately by a 500m run — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Row + Run (B) Badge",
    participants: 23,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Row", current: 0, goal: 500, unit: "m" },
      { label: "Run", current: 0, goal: 500, unit: "m" },
    ],
    leaderboard: [{ id: "hcrrb-1", name: "Maya Kowalski", initials: "MK", score: 1 }],
  },
  {
    id: "hyrox-combo-bike-run-a",
    title: "Bike + Run (A)",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "5K Bike + 1K Run",
    duration: "1 Month",
    description: "Complete this HYROX combo — a 5K bike followed immediately by a 1K run — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Bike + Run (A) Badge",
    participants: 30,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Bike", current: 0, goal: 5000, unit: "m" },
      { label: "Run", current: 0, goal: 1000, unit: "m" },
    ],
    leaderboard: [{ id: "hcbra-1", name: "Priya Shah", initials: "PS", score: 1 }],
  },
  {
    id: "hyrox-combo-bike-run-b",
    title: "Bike + Run (B)",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "3K Bike + 500m Run",
    duration: "1 Month",
    description: "Complete this HYROX combo — a 3K bike followed immediately by a 500m run — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Bike + Run (B) Badge",
    participants: 25,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Bike", current: 0, goal: 3000, unit: "m" },
      { label: "Run", current: 0, goal: 500, unit: "m" },
    ],
    leaderboard: [{ id: "hcbrb-1", name: "Wren Torres", initials: "WT", score: 1 }],
  },
  {
    id: "hyrox-combo-ski-row-bike",
    title: "Ski + Row + Bike",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "250m Ski + 500m Row + 2K Bike",
    duration: "1 Month",
    description: "Complete this HYROX combo — 250m Ski erg, 500m row, and a 2K bike, back to back — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Ski + Row + Bike Badge",
    participants: 16,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Ski", current: 0, goal: 250, unit: "m" },
      { label: "Row", current: 0, goal: 500, unit: "m" },
      { label: "Bike", current: 0, goal: 2000, unit: "m" },
    ],
    leaderboard: [{ id: "hcsrbi-1", name: "Coach Rex", initials: "CR", score: 1 }],
  },
  {
    id: "hyrox-combo-ski-row-run",
    title: "Ski + Row + Run",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "250m Ski + 500m Row + 750m Run",
    duration: "1 Month",
    description: "Complete this HYROX combo — 250m Ski erg, 500m row, and a 750m run, back to back — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Ski + Row + Run Badge",
    participants: 14,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Ski", current: 0, goal: 250, unit: "m" },
      { label: "Row", current: 0, goal: 500, unit: "m" },
      { label: "Run", current: 0, goal: 750, unit: "m" },
    ],
    leaderboard: [{ id: "hcsrr-1", name: "Elena Cruz", initials: "EC", score: 1 }],
  },
  {
    id: "hyrox-combo-ski-bike-run",
    title: "Ski + Bike + Run",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "250m Ski + 2K Bike + 500m Run",
    duration: "1 Month",
    description: "Complete this HYROX combo — 250m Ski erg, a 2K bike, and a 500m run, back to back — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Ski + Bike + Run Badge",
    participants: 15,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Ski", current: 0, goal: 250, unit: "m" },
      { label: "Bike", current: 0, goal: 2000, unit: "m" },
      { label: "Run", current: 0, goal: 500, unit: "m" },
    ],
    leaderboard: [{ id: "hcsbr-1", name: "Marcus Lee", initials: "ML", score: 1 }],
  },
  {
    id: "hyrox-combo-row-bike-run",
    title: "Row + Bike + Run",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "500m Row + 2K Bike + 500m Run",
    duration: "1 Month",
    description: "Complete this HYROX combo — 500m row, a 2K bike, and a 500m run, back to back — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Row + Bike + Run Badge",
    participants: 17,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Row", current: 0, goal: 500, unit: "m" },
      { label: "Bike", current: 0, goal: 2000, unit: "m" },
      { label: "Run", current: 0, goal: 500, unit: "m" },
    ],
    leaderboard: [{ id: "hcrbr-1", name: "Jonas Bauer", initials: "JB", score: 1 }],
  },
  {
    id: "hyrox-combo-full-send",
    title: "Full Send",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "250m Ski + 500m Row + 1.5K Bike + 500m Run",
    duration: "1 Month",
    description: "Complete this HYROX combo — 250m Ski erg, 500m row, a 1.5K bike, and a 500m run, all four engine movements back to back — in one session, then log your finish.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Full Send Badge",
    participants: 12,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    components: [
      { label: "Ski", current: 0, goal: 250, unit: "m" },
      { label: "Row", current: 0, goal: 500, unit: "m" },
      { label: "Bike", current: 0, goal: 1500, unit: "m" },
      { label: "Run", current: 0, goal: 500, unit: "m" },
    ],
    leaderboard: [{ id: "hcfs-1", name: "Deshawn Walker", initials: "DW", score: 1 }],
  },
  {
    id: "deka-fit-finisher",
    title: "DEKA FIT Finisher",
    sub: "DEKA · Ends in 7 days",
    category: "DEKA",
    goal: "Finish a DEKA FIT event",
    duration: "1 Month",
    description: "Complete a DEKA FIT event this month — 23 zones, your pace. Log your finish to complete this challenge.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos DEKA FIT Finisher Badge",
    participants: 53,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "deka-c-1", name: "Maya Kowalski", initials: "MK", score: 1 }],
  },
  {
    id: "public-safety-foundation-finisher",
    title: "Foundation Finisher",
    sub: "Public Safety Prep · Ends in 7 days",
    category: "Public Safety Prep",
    goal: "Complete the Foundation cycle",
    duration: "1 Month",
    description: "Complete the Foundation training cycle of your Fire Dept or Law Enforcement prep track this month.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Foundation Finisher Badge",
    participants: 29,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "psp-1", name: "Priya Shah", initials: "PS", score: 1 }],
  },
];

export const leaderboard = [
  { id: "l1", rank: 1, name: "Elena Cruz", initials: "EC", score: 12480, unit: "pts", trend: "same" },
  { id: "l2", rank: 2, name: "Marcus Lee", initials: "ML", score: 12105, unit: "pts", trend: "up" },
  { id: "l3", rank: 3, name: "You", initials: "YO", score: 11870, unit: "pts", trend: "up", isSelf: true },
  { id: "l4", rank: 4, name: "Priya Shah", initials: "PS", score: 11340, unit: "pts", trend: "down" },
  { id: "l5", rank: 5, name: "Deshawn W.", initials: "DW", score: 10990, unit: "pts", trend: "same" },
];

export const feedPosts = [
  {
    id: "p1",
    user: { name: "Maya Kowalski", initials: "MK", handle: "@maya.runs", athleteId: "maya" },
    time: "22m ago",
    type: "Run",
    title: "Tempo run — new 10K PR",
    stats: [
      { label: "Distance", value: "10.2 km" },
      { label: "Pace", value: "4:12 /km" },
      { label: "Time", value: "42:51" },
    ],
    caption: "Chased that sub-43 for months. Legs are toast but worth it 🔥",
    likes: 128,
    comments: [
      { id: "cm1", user: "Deshawn", text: "LET'S GO. That pace is unreal." },
      { id: "cm2", user: "Coach Rex", text: "Splits looked perfectly even. Nice pacing." },
    ],
    liked: false,
  },
  {
    id: "p2",
    user: { name: "Deshawn Walker", initials: "DW", handle: "@dwalks_heavy", athleteId: "deshawn" },
    time: "1h ago",
    type: "Strength",
    title: "Leg day — PR on back squat",
    stats: [
      { label: "Lift", value: "Back Squat" },
      { label: "Max", value: "182.5 kg" },
      { label: "Sets", value: "5x3" },
    ],
    caption: "Finally broke through the plateau. Onto 185 next week.",
    likes: 96,
    comments: [{ id: "cm3", user: "Maya", text: "Insane depth on that last rep" }],
    liked: true,
  },
  {
    id: "p3",
    user: { name: "Priya Shah", initials: "PS", handle: "@priya.climbs", athleteId: "priya" },
    time: "3h ago",
    type: "Ride",
    title: "Sunday long ride — Vert Gains challenge",
    stats: [
      { label: "Distance", value: "64.3 km" },
      { label: "Elevation", value: "1,140 m" },
      { label: "Avg Power", value: "212 W" },
    ],
    caption: "Climbed until my legs gave up. Vert Gains leaderboard, I'm coming for you.",
    likes: 74,
    comments: [],
    liked: false,
  },
];
