export const stories = [
  { id: "you", name: "Your Story", initials: "YO", isSelf: true, viewed: false },
  { id: "u1", name: "Maya K.", initials: "MK", viewed: false },
  { id: "u2", name: "Deshawn", initials: "DW", viewed: false },
  { id: "u3", name: "Elena", initials: "EL", viewed: true },
  { id: "u4", name: "Priya", initials: "PS", viewed: false },
  { id: "u5", name: "Coach Rex", initials: "CR", viewed: false },
  { id: "u6", name: "Jonas", initials: "JB", viewed: true },
  { id: "u7", name: "Wren", initials: "WT", viewed: true },
];

export const sponsoredAd = {
  brand: "SurgeFuel",
  tagline: "Electrolytes built for race day. 0 sugar, all send.",
  cta: "Shop Now",
  badge: "SF",
};

// Every challenge belongs to exactly one activity category — CHALLENGE_CATEGORIES below is
// the canonical ordered list the Challenges tab groups by. Running is fully populated;
// everything else has at least one example so the category/accordion structure and
// navigation can be verified end-to-end even before those lists are fleshed out for real.
export const CHALLENGE_CATEGORIES = [
  "Running",
  "Biking",
  "Skiing",
  "Rowing",
  "Olympic Weightlifting",
  "HYROX",
  "DEKA",
  "Strength & Conditioning",
  "CrossFit",
  "Public Safety Prep",
];

export const challenges = [
  {
    id: "c1",
    title: "100K in August",
    sub: "Running · Ends in 22 days",
    category: "Running",
    goal: "100 kilometers",
    duration: "1 Month",
    description:
      "Log 100 kilometers of running before the month is out. Tempo runs, long runs, easy shakeouts — every logged run counts toward your total distance.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Finisher Badge + $50 Gear Credit",
    participants: 4821,
    progress: 62,
    joined: true,
    unit: "km",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "c1-1", name: "Elena Cruz", initials: "EC", score: 84.2 },
      { id: "c1-2", name: "Marcus Lee", initials: "ML", score: 79.5 },
      { id: "c1-6", name: "Maya Kowalski", initials: "MK", score: 71.0 },
      { id: "c1-3", name: "You", initials: "YO", score: 62.0, isSelf: true },
      { id: "c1-4", name: "Priya Shah", initials: "PS", score: 58.3 },
      { id: "c1-5", name: "Deshawn W.", initials: "DW", score: 51.7 },
    ],
  },
  {
    id: "c2",
    title: "Sunrise Squad",
    sub: "Running · 5 AM sessions · 7 day streak",
    category: "Running",
    goal: "7 day streak",
    duration: "1 Week",
    description:
      "Beat the sunrise. Log a training session before 6 AM every day for 7 days straight to keep your streak alive — miss a day and it resets.",
    startDate: "Aug 3, 2026",
    endDate: "Aug 10, 2026",
    prize: "Sunrise Squad Trophy Icon",
    participants: 1209,
    progress: 30,
    joined: false,
    unit: "day streak",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "c2-1", name: "Wren Torres", initials: "WT", score: 7 },
      { id: "c2-2", name: "Jonas B.", initials: "JB", score: 6 },
      { id: "c2-3", name: "Coach Rex", initials: "CR", score: 5 },
      { id: "c2-4", name: "Maya K.", initials: "MK", score: 4 },
    ],
  },
  {
    id: "c3",
    title: "Iron Grip",
    sub: "Strength & Conditioning · Ends in 5 days",
    category: "Strength & Conditioning",
    goal: "Max deadlift volume",
    duration: "2 Weeks",
    description:
      "Total deadlift volume challenge. Log your heaviest working sets — weight × reps determines your total volume and your rank on the board.",
    startDate: "Jul 29, 2026",
    endDate: "Aug 14, 2026",
    prize: "Iron Grip Chalk Bag + Leaderboard Feature",
    participants: 976,
    progress: 88,
    joined: false,
    unit: "kg vol",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "c3-1", name: "Deshawn Walker", initials: "DW", score: 14820 },
      { id: "c3-2", name: "Marcus Lee", initials: "ML", score: 13990 },
      { id: "c3-3", name: "Elena Cruz", initials: "EC", score: 11200 },
      { id: "c3-4", name: "Priya Shah", initials: "PS", score: 9840 },
    ],
  },
  {
    id: "c4",
    title: "Vert Gains",
    sub: "Biking · Elevation climbed · Ends in 14 days",
    category: "Biking",
    goal: "Max elevation climbed",
    duration: "2 Weeks",
    description:
      "Climb as much elevation as you can. Every ride's elevation gain counts toward your monthly total — hills, mountains, repeats, all of it.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 15, 2026",
    prize: "KOM Jersey Giveaway Entry",
    participants: 542,
    progress: 15,
    joined: false,
    unit: "m",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "c4-1", name: "Priya Shah", initials: "PS", score: 4120 },
      { id: "c4-2", name: "Coach Rex", initials: "CR", score: 3580 },
      { id: "c4-3", name: "Wren Torres", initials: "WT", score: 2990 },
      { id: "c4-4", name: "Jonas B.", initials: "JB", score: 2210 },
    ],
  },
  // Weekly Running mileage challenges — 1-week window, progress tracked toward each
  // challenge's mile goal the same way every other challenge tracks its own unit.
  {
    id: "wk-run-5",
    title: "Run 5",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "5 miles",
    duration: "1 Week",
    description: "Log 5 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 5 Badge",
    participants: 2140,
    progress: 100,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wk5-1", name: "Elena Cruz", initials: "EC", score: 5.8 },
      { id: "wk5-2", name: "You", initials: "YO", score: 5.0, isSelf: true },
      { id: "wk5-3", name: "Jonas B.", initials: "JB", score: 4.6 },
    ],
  },
  {
    id: "wk-run-10",
    title: "Run 10",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "10 miles",
    duration: "1 Week",
    description: "Log 10 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 10 Badge",
    participants: 1875,
    progress: 100,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wk10-1", name: "Maya Kowalski", initials: "MK", score: 14.2 },
      { id: "wk10-2", name: "You", initials: "YO", score: 10.0, isSelf: true },
      { id: "wk10-3", name: "Wren Torres", initials: "WT", score: 9.1 },
    ],
  },
  {
    id: "wk-run-15",
    title: "Run 15",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "15 miles",
    duration: "1 Week",
    description: "Log 15 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 15 Badge",
    participants: 1402,
    progress: 60,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wk15-1", name: "Maya Kowalski", initials: "MK", score: 13.5 },
      { id: "wk15-2", name: "You", initials: "YO", score: 9.0, isSelf: true },
      { id: "wk15-3", name: "Coach Rex", initials: "CR", score: 6.2 },
    ],
  },
  {
    id: "wk-run-20",
    title: "Run 20",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "20 miles",
    duration: "1 Week",
    description: "Log 20 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 20 Badge",
    participants: 968,
    progress: 40,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wk20-1", name: "Maya Kowalski", initials: "MK", score: 17.0 },
      { id: "wk20-2", name: "You", initials: "YO", score: 8.0, isSelf: true },
      { id: "wk20-3", name: "Priya Shah", initials: "PS", score: 5.4 },
    ],
  },
  {
    id: "wk-run-30",
    title: "Run 30",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "30 miles",
    duration: "1 Week",
    description: "Log 30 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 30 Badge",
    participants: 511,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wk30-1", name: "Maya Kowalski", initials: "MK", score: 22.4 },
      { id: "wk30-2", name: "Elena Cruz", initials: "EC", score: 18.9 },
    ],
  },
  {
    id: "wk-run-40",
    title: "Run 40",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "40 miles",
    duration: "1 Week",
    description: "Log 40 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 40 Badge",
    participants: 284,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "wk40-1", name: "Maya Kowalski", initials: "MK", score: 28.1 },
      { id: "wk40-2", name: "Marcus Lee", initials: "ML", score: 19.6 },
    ],
  },
  {
    id: "wk-run-50",
    title: "Run 50",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "50 miles",
    duration: "1 Week",
    description: "Log 50 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 50 Badge",
    participants: 132,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "wk50-1", name: "Maya Kowalski", initials: "MK", score: 31.7 }],
  },
  {
    id: "wk-run-60",
    title: "Run 60",
    sub: "Running · Ends in 6 days",
    category: "Running",
    goal: "60 miles",
    duration: "1 Week",
    description: "Log 60 miles of running within one week to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Run 60 Badge",
    participants: 47,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "wk60-1", name: "Maya Kowalski", initials: "MK", score: 34.0 }],
  },
  // Monthly Running mileage challenges — 1-month window, same progress-tracking pattern.
  {
    id: "mo-run-10",
    title: "Monthly 10",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "10 miles",
    duration: "1 Month",
    description: "Log 10 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Monthly 10 Badge",
    participants: 2984,
    progress: 100,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "mo10-1", name: "Elena Cruz", initials: "EC", score: 24.8 },
      { id: "mo10-2", name: "You", initials: "YO", score: 10.0, isSelf: true },
      { id: "mo10-3", name: "Jonas B.", initials: "JB", score: 9.2 },
    ],
  },
  {
    id: "mo-run-20",
    title: "Monthly 20",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "20 miles",
    duration: "1 Month",
    description: "Log 20 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Monthly 20 Badge",
    participants: 2317,
    progress: 100,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "mo20-1", name: "Maya Kowalski", initials: "MK", score: 46.5 },
      { id: "mo20-2", name: "You", initials: "YO", score: 20.0, isSelf: true },
      { id: "mo20-3", name: "Wren Torres", initials: "WT", score: 18.3 },
    ],
  },
  {
    id: "mo-run-30",
    title: "Monthly 30",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "30 miles",
    duration: "1 Month",
    description: "Log 30 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Monthly 30 Badge",
    participants: 1690,
    progress: 70,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "mo30-1", name: "Maya Kowalski", initials: "MK", score: 52.0 },
      { id: "mo30-2", name: "You", initials: "YO", score: 21.0, isSelf: true },
      { id: "mo30-3", name: "Coach Rex", initials: "CR", score: 17.4 },
    ],
  },
  {
    id: "mo-run-40",
    title: "Monthly 40",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "40 miles",
    duration: "1 Month",
    description: "Log 40 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Monthly 40 Badge",
    participants: 1104,
    progress: 45,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "mo40-1", name: "Maya Kowalski", initials: "MK", score: 61.8 },
      { id: "mo40-2", name: "You", initials: "YO", score: 18.0, isSelf: true },
      { id: "mo40-3", name: "Priya Shah", initials: "PS", score: 12.5 },
    ],
  },
  {
    id: "mo-run-50",
    title: "Monthly 50",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "50 miles",
    duration: "1 Month",
    description: "Log 50 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Monthly 50 Badge",
    participants: 742,
    progress: 20,
    joined: true,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "mo50-1", name: "Maya Kowalski", initials: "MK", score: 68.4 },
      { id: "mo50-2", name: "Elena Cruz", initials: "EC", score: 33.1 },
      { id: "mo50-3", name: "You", initials: "YO", score: 10.0, isSelf: true },
    ],
  },
  {
    id: "mo-run-60",
    title: "Monthly 60",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "60 miles",
    duration: "1 Month",
    description: "Log 60 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Monthly 60 Badge",
    participants: 398,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [
      { id: "mo60-1", name: "Maya Kowalski", initials: "MK", score: 74.2 },
      { id: "mo60-2", name: "Marcus Lee", initials: "ML", score: 41.0 },
    ],
  },
  {
    id: "mo-run-75",
    title: "Monthly 75",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "75 miles",
    duration: "1 Month",
    description: "Log 75 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Monthly 75 Badge",
    participants: 215,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "mo75-1", name: "Maya Kowalski", initials: "MK", score: 81.6 }],
  },
  {
    id: "mo-century-run",
    title: "Century Run",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "100 miles",
    duration: "1 Month",
    description: "Log 100 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Century Badge",
    participants: 109,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "mocent-1", name: "Maya Kowalski", initials: "MK", score: 94.3 }],
  },
  {
    id: "mo-run-150",
    title: "Run 150",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "150 miles",
    duration: "1 Month",
    description: "Log 150 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Run 150 Badge",
    participants: 38,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "mo150-1", name: "Maya Kowalski", initials: "MK", score: 112.0 }],
  },
  {
    id: "mo-run-200",
    title: "Run 200",
    sub: "Running · Ends in 7 days",
    category: "Running",
    goal: "200 miles",
    duration: "1 Month",
    description: "Log 200 miles of running within the month to complete this challenge. Every tracked run counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Run 200 Badge",
    participants: 14,
    progress: 0,
    joined: false,
    unit: "mi",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "mo200-1", name: "Maya Kowalski", initials: "MK", score: 121.5 }],
  },
  // Placeholder examples for the remaining categories — enough to prove the accordion/detail
  // structure and navigation work end-to-end; full lists for these can come later.
  {
    id: "ski-vertical",
    title: "Vertical Descent",
    sub: "Skiing · Ends in 7 days",
    category: "Skiing",
    goal: "20,000 vertical feet",
    duration: "1 Month",
    description: "Ski 20,000 vertical feet of descent within the month. Every tracked run down the mountain counts toward your total.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Vertical Descent Badge",
    participants: 62,
    progress: 0,
    joined: false,
    unit: "ft",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "ski-1", name: "Coach Rex", initials: "CR", score: 8400 }],
  },
  {
    id: "row-10k",
    title: "Row 10K",
    sub: "Rowing · Ends in 6 days",
    category: "Rowing",
    goal: "10,000 meters",
    duration: "1 Week",
    description: "Row 10,000 meters within one week to complete this challenge. Erg or water — every tracked meter counts.",
    startDate: "Aug 24, 2026",
    endDate: "Aug 30, 2026",
    prize: "Kairos Row 10K Badge",
    participants: 89,
    progress: 0,
    joined: false,
    unit: "m",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "row-1", name: "Wren Torres", initials: "WT", score: 6200 }],
  },
  {
    id: "oly-new-snatch-pr",
    title: "New Snatch PR",
    sub: "Olympic Weightlifting · Ends in 7 days",
    category: "Olympic Weightlifting",
    goal: "Set a new snatch PR",
    duration: "1 Month",
    description: "Set a new personal record on the snatch this month. Submit your best make with a video or photo of the lift.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Snatch PR Badge",
    participants: 41,
    progress: 0,
    joined: false,
    unit: "kg",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "oly-1", name: "Marcus Lee", initials: "ML", score: 92 }],
  },
  {
    id: "hyrox-simulation",
    title: "HYROX Simulation",
    sub: "HYROX · Ends in 7 days",
    category: "HYROX",
    goal: "Complete a full HYROX simulation",
    duration: "1 Month",
    description: "Complete a full HYROX simulation — all 8 stations and runs, at race pace — sometime this month.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos HYROX Simulation Badge",
    participants: 76,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "hyrox-c-1", name: "Deshawn Walker", initials: "DW", score: 1 }],
  },
  {
    id: "deka-fit-finisher",
    title: "DEKA FIT Finisher",
    sub: "DEKA · Ends in 7 days",
    category: "DEKA",
    goal: "Finish a DEKA FIT event",
    duration: "1 Month",
    description: "Complete a DEKA FIT event this month — 23 zones, your pace. Log your finish to complete this challenge.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos DEKA FIT Finisher Badge",
    participants: 53,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "deka-c-1", name: "Maya Kowalski", initials: "MK", score: 1 }],
  },
  {
    id: "crossfit-total",
    title: "CrossFit Total",
    sub: "CrossFit · Ends in 7 days",
    category: "CrossFit",
    goal: "New CrossFit Total",
    duration: "1 Month",
    description: "Set a new CrossFit Total — best back squat, shoulder press, and deadlift combined — this month.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos CrossFit Total Badge",
    participants: 118,
    progress: 0,
    joined: false,
    unit: "kg",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "cf-1", name: "Deshawn Walker", initials: "DW", score: 420 }],
  },
  {
    id: "public-safety-foundation-finisher",
    title: "Foundation Finisher",
    sub: "Public Safety Prep · Ends in 7 days",
    category: "Public Safety Prep",
    goal: "Complete the Foundation cycle",
    duration: "1 Month",
    description: "Complete the Foundation training cycle of your Fire Dept or Law Enforcement prep track this month.",
    startDate: "Aug 1, 2026",
    endDate: "Aug 31, 2026",
    prize: "Kairos Foundation Finisher Badge",
    participants: 29,
    progress: 0,
    joined: false,
    unit: "completions",
    accent: "from-rival-red to-rival-red-dim",
    leaderboard: [{ id: "psp-1", name: "Priya Shah", initials: "PS", score: 1 }],
  },
];

export const leaderboard = [
  { id: "l1", rank: 1, name: "Elena Cruz", initials: "EC", score: 12480, unit: "pts", trend: "same" },
  { id: "l2", rank: 2, name: "Marcus Lee", initials: "ML", score: 12105, unit: "pts", trend: "up" },
  { id: "l3", rank: 3, name: "You", initials: "YO", score: 11870, unit: "pts", trend: "up", isSelf: true },
  { id: "l4", rank: 4, name: "Priya Shah", initials: "PS", score: 11340, unit: "pts", trend: "down" },
  { id: "l5", rank: 5, name: "Deshawn W.", initials: "DW", score: 10990, unit: "pts", trend: "same" },
];

export const feedPosts = [
  {
    id: "p1",
    user: { name: "Maya Kowalski", initials: "MK", handle: "@maya.runs", athleteId: "maya" },
    time: "22m ago",
    type: "Run",
    title: "Tempo run — new 10K PR",
    stats: [
      { label: "Distance", value: "10.2 km" },
      { label: "Pace", value: "4:12 /km" },
      { label: "Time", value: "42:51" },
    ],
    caption: "Chased that sub-43 for months. Legs are toast but worth it 🔥",
    likes: 128,
    comments: [
      { id: "cm1", user: "Deshawn", text: "LET'S GO. That pace is unreal." },
      { id: "cm2", user: "Coach Rex", text: "Splits looked perfectly even. Nice pacing." },
    ],
    liked: false,
  },
  {
    id: "p2",
    user: { name: "Deshawn Walker", initials: "DW", handle: "@dwalks_heavy", athleteId: "deshawn" },
    time: "1h ago",
    type: "Strength",
    title: "Leg day — PR on back squat",
    stats: [
      { label: "Lift", value: "Back Squat" },
      { label: "Max", value: "182.5 kg" },
      { label: "Sets", value: "5x3" },
    ],
    caption: "Finally broke through the plateau. Onto 185 next week.",
    likes: 96,
    comments: [{ id: "cm3", user: "Maya", text: "Insane depth on that last rep" }],
    liked: true,
  },
  {
    id: "p3",
    user: { name: "Priya Shah", initials: "PS", handle: "@priya.climbs", athleteId: "priya" },
    time: "3h ago",
    type: "Ride",
    title: "Sunday long ride — Vert Gains challenge",
    stats: [
      { label: "Distance", value: "64.3 km" },
      { label: "Elevation", value: "1,140 m" },
      { label: "Avg Power", value: "212 W" },
    ],
    caption: "Climbed until my legs gave up. Vert Gains leaderboard, I'm coming for you.",
    likes: 74,
    comments: [],
    liked: false,
  },
];
