export const programCategories = ["HYROX", "DEKA", "Running", "Strength & Conditioning"];

// HYROX programs are already split into Beginner/Intermediate/Advanced cards, so they don't get a selector.
export const categoriesWithLevelSelector = ["DEKA", "Running", "Strength & Conditioning"];

export const programs = [
  {
    id: "p1",
    title: "HYROX Beginner",
    category: "HYROX",
    duration: 8,
    difficulty: "Beginner",
    shortDescription: "Learn the eight HYROX stations and build the base fitness to finish strong.",
    fullDescription:
      "An 8-week on-ramp for first-time HYROX athletes. Covers proper technique for every station, builds running consistency, and layers in compromised running so race day doesn't come as a shock.",
    coach: {
      name: "Elena Cruz",
      initials: "EC",
      title: "HYROX Coach & Running Specialist",
      bio: "Coaches first-timers through their debut HYROX events with a focus on technique before intensity.",
    },
    enrolledCount: 963,
    joined: false,
    currentWeek: 0,
    weeks: [
      { week: 1, title: "Meet the Stations", focus: "Technique walkthrough for all eight stations" },
      { week: 2, title: "Running Consistency", focus: "Establishing a repeatable easy running pace" },
      { week: 3, title: "Sled Basics", focus: "Push and pull technique, light loads" },
      { week: 4, title: "Carries & Grip", focus: "Farmer's carry and sandbag lunge volume" },
      { week: 5, title: "Compromised Running I", focus: "Short runs off station fatigue" },
      { week: 6, title: "Compromised Running II", focus: "Longer runs off station fatigue" },
      { week: 7, title: "Full Station Walkthrough", focus: "All eight stations back to back, easy pace" },
      { week: 8, title: "Race Week Prep", focus: "Deload and race-day logistics" },
    ],
  },
  {
    id: "p2",
    title: "HYROX Intermediate",
    category: "HYROX",
    duration: 10,
    difficulty: "Intermediate",
    shortDescription: "Race-specific engine and station work to peak for your next HYROX.",
    fullDescription:
      "A 10-week block built around HYROX's eight-station format — running intervals paired with sled pushes, wall balls, farmer's carries, and burpee broad jumps. Designed to build the mixed aerobic-strength engine HYROX demands, with a taper in the final week so you toe the line fresh.",
    coach: {
      name: "Coach Rex",
      initials: "CR",
      title: "Certified HYROX Coach",
      bio: "Former HYROX Open podium finisher turned coach. Programs 200+ athletes through race prep every season.",
    },
    enrolledCount: 1842,
    joined: true,
    currentWeek: 4,
    weeks: [
      { week: 1, title: "Foundation & Testing", focus: "Baseline 1km run + station technique check" },
      { week: 2, title: "Aerobic Base", focus: "Zone 2 running volume + compromised running intro" },
      { week: 3, title: "Station Strength", focus: "Heavy sled work and carries, moderate running" },
      { week: 4, title: "Engine Building", focus: "Interval running under fatigue" },
      { week: 5, title: "Mixed Modal", focus: "Full station circuits at race pace" },
      { week: 6, title: "Peak Volume", focus: "Highest weekly training load of the block" },
      { week: 7, title: "Race Simulation", focus: "Half-distance HYROX simulation" },
      { week: 8, title: "Strength Retention", focus: "Maintain power output, reduce volume" },
      { week: 9, title: "Sharpen", focus: "Race-pace intervals and technique polish" },
      { week: 10, title: "Taper & Race Week", focus: "Deload, mobility, and race day" },
    ],
  },
  {
    id: "p3",
    title: "HYROX Advanced",
    category: "HYROX",
    duration: 10,
    difficulty: "Advanced",
    shortDescription: "A race-simulation-heavy block for athletes chasing a podium finish.",
    fullDescription:
      "Ten weeks of high-volume running and near-maximal station loading, capped with two full race simulations. Built for experienced HYROX athletes with at least one race under their belt.",
    coach: {
      name: "Marcus Lee",
      initials: "ML",
      title: "HYROX Performance Coach",
      bio: "Coaches podium-track HYROX athletes on race pacing, station efficiency, and peak-week strategy.",
    },
    enrolledCount: 512,
    joined: false,
    currentWeek: 0,
    weeks: [
      { week: 1, title: "Performance Testing", focus: "Baseline benchmarks across all eight stations" },
      { week: 2, title: "High Volume Running", focus: "Elevated mileage under normal fatigue" },
      { week: 3, title: "Heavy Station Load", focus: "Max-effort sled and carry work" },
      { week: 4, title: "Race Pace Intervals", focus: "Running intervals at target race pace" },
      { week: 5, title: "Compromised Running Intensives", focus: "Hard running off heavy station fatigue" },
      { week: 6, title: "Peak Volume", focus: "Highest combined running and station load" },
      { week: 7, title: "Full Race Simulation", focus: "Complete HYROX simulation at race intensity" },
      { week: 8, title: "Power Retention", focus: "Maintain intensity, trim volume" },
      { week: 9, title: "Sharpen & Simulate", focus: "Second full race simulation" },
      { week: 10, title: "Taper & Race Week", focus: "Deload into race day" },
    ],
  },
  {
    id: "p4",
    title: "DEKA FIT",
    category: "DEKA",
    duration: 12,
    difficulty: "Intermediate",
    shortDescription: "Balanced strength-and-cardio prep for DEKA FIT's 10 functional zones.",
    fullDescription:
      "A 12-week program blending running with strength-endurance zone work, built for athletes preparing for DEKA FIT's 10-zone format.",
    coach: {
      name: "Priya Shah",
      initials: "PS",
      title: "DEKA Fit Coach",
      bio: "Builds balanced strength-and-endurance programming for athletes across all DEKA event formats.",
    },
    enrolledCount: 745,
    joined: true,
    currentWeek: 5,
    enrolledLevel: "Beginner",
    weeks: [
      { week: 1, title: "Zone Familiarization", focus: "Technique for all 10 DEKA FIT zones" },
      { week: 2, title: "Aerobic Base", focus: "Running volume between zone work" },
      { week: 3, title: "Strength Base", focus: "Building capacity in strength zones" },
      { week: 4, title: "Zone Circuits I", focus: "Grouped zones at moderate pace" },
      { week: 5, title: "Compromised Running I", focus: "Running off zone fatigue" },
      { week: 6, title: "Zone Circuits II", focus: "Grouped zones at race pace" },
      { week: 7, title: "Compromised Running II", focus: "Longer runs off zone fatigue" },
      { week: 8, title: "Peak Volume", focus: "Highest combined running and zone load" },
      { week: 9, title: "Full Zone Simulation I", focus: "All 10 zones plus running in sequence" },
      { week: 10, title: "Full Zone Simulation II", focus: "Repeat simulation at race intensity" },
      { week: 11, title: "Sharpen", focus: "Race-pace zones and running polish" },
      { week: 12, title: "Taper", focus: "Deload and race-day prep" },
    ],
  },
  {
    id: "p5",
    title: "DEKA STRONG",
    category: "DEKA",
    duration: 12,
    difficulty: "Advanced",
    shortDescription: "Strength-biased prep for DEKA STRONG's 23 functional zones.",
    fullDescription:
      "Twelve weeks targeting the strength-endurance blend DEKA STRONG demands — sandbag work, sled work, rope climbs, and odd-object carries under time pressure across all 23 zones.",
    coach: {
      name: "Marcus Lee",
      initials: "ML",
      title: "DEKA Fit Coach",
      bio: "Specializes in functional strength programming for hybrid athletes competing in DEKA events.",
    },
    enrolledCount: 587,
    joined: false,
    currentWeek: 0,
    weeks: [
      { week: 1, title: "Zone Familiarization", focus: "Technique for every DEKA STRONG zone" },
      { week: 2, title: "Strength Base", focus: "Building raw strength in key lifts" },
      { week: 3, title: "Carry Capacity", focus: "Loaded carries and grip endurance" },
      { week: 4, title: "Zone Circuits I", focus: "Grouped zones at moderate intensity" },
      { week: 5, title: "Grip & Pull Volume", focus: "Rope climbs and pulling strength" },
      { week: 6, title: "Zone Circuits II", focus: "Grouped zones at race intensity" },
      { week: 7, title: "Strength Intensity", focus: "Heavier loads across key zone lifts" },
      { week: 8, title: "Carry & Grip Peak", focus: "Highest carry and grip volume of the block" },
      { week: 9, title: "Full Zone Simulation I", focus: "All 23 zones in sequence" },
      { week: 10, title: "Full Zone Simulation II", focus: "Repeat simulation at race intensity" },
      { week: 11, title: "Sharpen", focus: "Technique polish and race-pace zones" },
      { week: 12, title: "Taper", focus: "Deload and movement prep for race day" },
    ],
  },
  {
    id: "p6",
    title: "DEKA MILE",
    category: "DEKA",
    duration: 12,
    difficulty: "Beginner",
    shortDescription: "Build the aerobic engine to move fast between DEKA MILE's 10 zones.",
    fullDescription:
      "A 12-week endurance-first program pairing steady running with light functional zone work, built for athletes tackling their first DEKA MILE.",
    coach: {
      name: "Priya Shah",
      initials: "PS",
      title: "Endurance Coach",
      bio: "Builds aerobic bases for endurance and hybrid athletes across running, cycling, and functional racing.",
    },
    enrolledCount: 421,
    joined: false,
    currentWeek: 0,
    weeks: [
      { week: 1, title: "Base Building", focus: "Easy running volume, zone technique intro" },
      { week: 2, title: "Zone Intro", focus: "Light functional work between runs" },
      { week: 3, title: "Aerobic Volume I", focus: "Building weekly running volume" },
      { week: 4, title: "Tempo + Zones I", focus: "Tempo running paired with zone circuits" },
      { week: 5, title: "Zone Circuit Practice I", focus: "Grouped zones at moderate pace" },
      { week: 6, title: "Aerobic Volume II", focus: "Continued running buildup" },
      { week: 7, title: "Tempo + Zones II", focus: "Tempo running at increased zone intensity" },
      { week: 8, title: "Endurance Volume", focus: "Peak weekly running mileage" },
      { week: 9, title: "Zone Circuit Practice II", focus: "All 10 zones run through in sequence" },
      { week: 10, title: "Full Zone Simulation", focus: "Complete DEKA MILE simulation" },
      { week: 11, title: "Taper Begins", focus: "Reduced volume, legs freshening up" },
      { week: 12, title: "Race Week", focus: "Deload and race-day pacing plan" },
    ],
  },
  {
    id: "p14",
    title: "DEKA ATLAS",
    category: "DEKA",
    duration: 12,
    difficulty: "Advanced",
    shortDescription: "The ultimate DEKA test — endurance and strength combined across an extended format.",
    fullDescription:
      "A 12-week peak program combining the running volume of DEKA MILE with the strength demands of DEKA STRONG, preparing athletes for DEKA ATLAS's extended combined format.",
    coach: {
      name: "Marcus Lee",
      initials: "ML",
      title: "DEKA Performance Coach",
      bio: "Coaches athletes through DEKA's most demanding combined running-and-strength formats.",
    },
    enrolledCount: 298,
    joined: false,
    currentWeek: 0,
    weeks: [
      { week: 1, title: "Zone & Distance Testing", focus: "Baseline benchmarks across zones and running" },
      { week: 2, title: "Aerobic Base", focus: "Building running volume alongside zone technique" },
      { week: 3, title: "Strength Base", focus: "Building capacity across all zone types" },
      { week: 4, title: "Zone Circuits I", focus: "Grouped zones at moderate intensity" },
      { week: 5, title: "Compromised Running I", focus: "Running under zone fatigue" },
      { week: 6, title: "Zone Circuits II", focus: "Grouped zones at increased intensity" },
      { week: 7, title: "Compromised Running II", focus: "Extended running under fatigue" },
      { week: 8, title: "Peak Volume", focus: "Highest combined running and zone load" },
      { week: 9, title: "Full Zone & Distance Simulation", focus: "Complete DEKA ATLAS simulation" },
      { week: 10, title: "Power Retention", focus: "Maintain intensity, trim volume" },
      { week: 11, title: "Sharpen", focus: "Race-pace zones and running polish" },
      { week: 12, title: "Taper & Race Week", focus: "Deload into race day" },
    ],
  },
  {
    id: "p15",
    title: "DEKA DOUBLE",
    category: "DEKA",
    duration: 12,
    difficulty: "Intermediate",
    shortDescription: "Double the distance, double the zones — an endurance-heavy DEKA build.",
    fullDescription:
      "A 12-week endurance-focused program built for DEKA DOUBLE's extended distance and zone count, layering running volume onto steady zone-circuit progression.",
    coach: {
      name: "Priya Shah",
      initials: "PS",
      title: "DEKA Endurance Coach",
      bio: "Prepares athletes for DEKA's extended-distance formats with a strength-endurance blend.",
    },
    enrolledCount: 214,
    joined: false,
    currentWeek: 0,
    weeks: [
      { week: 1, title: "Base Building", focus: "Establishing running and zone endurance" },
      { week: 2, title: "Aerobic Volume I", focus: "Extended easy running" },
      { week: 3, title: "Zone Endurance I", focus: "Zone work at extended volume" },
      { week: 4, title: "Aerobic Volume II", focus: "Continued running buildup" },
      { week: 5, title: "Zone Endurance II", focus: "Increasing zone circuit volume" },
      { week: 6, title: "Compromised Running I", focus: "Running off zone fatigue" },
      { week: 7, title: "Peak Volume I", focus: "High combined running and zone load" },
      { week: 8, title: "Compromised Running II", focus: "Extended running under fatigue" },
      { week: 9, title: "Peak Volume II", focus: "Highest weekly combined load" },
      { week: 10, title: "Full Distance Simulation", focus: "Complete DEKA DOUBLE simulation" },
      { week: 11, title: "Taper Begins", focus: "Reduced volume, race prep" },
      { week: 12, title: "Race Week", focus: "Full taper into race day" },
    ],
  },
  {
    id: "p8",
    title: "5K",
    category: "Running",
    duration: 6,
    difficulty: "Intermediate",
    shortDescription: "Sharpen your speed and dial in pacing to run your best 5K.",
    fullDescription:
      "A 6-week block combining tempo runs, VO2max intervals, and race-pace repeats for runners looking to PR their 5K.",
    coach: {
      name: "Maya Kowalski",
      initials: "MK",
      title: "USATF Level 2 Running Coach",
      bio: "Coaches competitive amateur runners chasing PRs from the mile to the marathon.",
    },
    enrolledCount: 1105,
    joined: false,
    currentWeek: 0,
    weeks: [
      { week: 1, title: "Threshold Base", focus: "Establishing lactate threshold pace" },
      { week: 2, title: "Speed Intro", focus: "Short intervals at 5K effort" },
      { week: 3, title: "Race Pace Repeats I", focus: "Repeats at target 5K pace" },
      { week: 4, title: "Volume Peak", focus: "Highest weekly mileage of the block" },
      { week: 5, title: "Race Pace Repeats II", focus: "Longer repeats at target pace" },
      { week: 6, title: "Taper & Race", focus: "Deload into race day" },
    ],
  },
  {
    id: "p16",
    title: "10K",
    category: "Running",
    duration: 8,
    difficulty: "Intermediate",
    shortDescription: "Bridge the gap from 5K fitness to a strong, confident 10K finish.",
    fullDescription:
      "An 8-week progression building weekly mileage and steady-state endurance to take you from 5K fitness to a confident 10K finish.",
    coach: {
      name: "Wren Torres",
      initials: "WT",
      title: "Distance Running Coach",
      bio: "Guides runners from their first 5K through longer distances with steady, sustainable progression.",
    },
    enrolledCount: 1476,
    joined: false,
    currentWeek: 0,
    weeks: [
      { week: 1, title: "Base Building", focus: "Establishing consistent running volume" },
      { week: 2, title: "Aerobic Volume I", focus: "Extending easy run distance" },
      { week: 3, title: "Tempo Intro", focus: "First tempo run of the block" },
      { week: 4, title: "Aerobic Volume II", focus: "Continued mileage buildup" },
      { week: 5, title: "Race Pace Intro", focus: "Short repeats at 10K effort" },
      { week: 6, title: "Peak Volume", focus: "Highest weekly mileage of the block" },
      { week: 7, title: "Race Pace Repeats", focus: "Longer repeats at 10K pace" },
      { week: 8, title: "Taper & Race", focus: "Deload into race day" },
    ],
  },
  {
    id: "p9",
    title: "Half Marathon",
    category: "Running",
    duration: 12,
    difficulty: "Intermediate",
    shortDescription: "Build the endurance and pacing to cross a half marathon finish line strong.",
    fullDescription:
      "A 12-week progression of long runs, tempo work, and easy mileage designed to get you race-ready for 21.1 kilometers.",
    coach: {
      name: "Elena Cruz",
      initials: "EC",
      title: "Endurance Running Coach",
      bio: "Guides runners from their first half marathon through PR attempts with a focus on smart mileage buildup.",
    },
    enrolledCount: 1348,
    joined: false,
    currentWeek: 0,
    weeks: [
      { week: 1, title: "Base Building", focus: "Establishing consistent weekly mileage" },
      { week: 2, title: "Aerobic Volume", focus: "Easy mileage buildup" },
      { week: 3, title: "Tempo Intro", focus: "First tempo run of the block" },
      { week: 4, title: "Long Run Progression I", focus: "Extending the weekly long run" },
      { week: 5, title: "Speed Intro", focus: "Short intervals to sharpen turnover" },
      { week: 6, title: "Long Run Progression II", focus: "Continued long run buildup" },
      { week: 7, title: "Peak Volume", focus: "Highest weekly mileage of the block" },
      { week: 8, title: "Race Pace Tempo", focus: "Tempo runs at goal race pace" },
      { week: 9, title: "Longest Run", focus: "Final and longest long run" },
      { week: 10, title: "Sharpening", focus: "Shorter, faster reps with recovery" },
      { week: 11, title: "Taper Begins", focus: "Reduced volume, legs freshening up" },
      { week: 12, title: "Race Week", focus: "Full taper into race day" },
    ],
  },
  {
    id: "p10",
    title: "Full Marathon",
    category: "Running",
    duration: 16,
    difficulty: "Advanced",
    shortDescription: "A complete 16-week buildup to race-day-ready marathon fitness.",
    fullDescription:
      "Sixteen weeks of progressive mileage, long runs, and race-pace tempo work for runners with a solid base preparing to take on 42.2 kilometers.",
    coach: {
      name: "Maya Kowalski",
      initials: "MK",
      title: "USATF Level 2 Running Coach",
      bio: "Coaches competitive amateur runners chasing PRs from the mile to the marathon.",
    },
    enrolledCount: 892,
    joined: false,
    currentWeek: 0,
    weeks: [
      { week: 1, title: "Base Building", focus: "Establishing consistent weekly mileage" },
      { week: 2, title: "Aerobic Volume I", focus: "Easy mileage buildup" },
      { week: 3, title: "Aerobic Volume II", focus: "Continued mileage buildup" },
      { week: 4, title: "Long Run Progression I", focus: "Extending the weekly long run" },
      { week: 5, title: "Tempo Intro", focus: "First tempo run of the block" },
      { week: 6, title: "Long Run Progression II", focus: "Continued long run buildup" },
      { week: 7, title: "Speed Intro", focus: "Short intervals to sharpen turnover" },
      { week: 8, title: "Peak Volume I", focus: "High weekly mileage phase begins" },
      { week: 9, title: "Long Run Progression III", focus: "Approaching peak long run distance" },
      { week: 10, title: "Peak Volume II", focus: "Highest weekly mileage of the block" },
      { week: 11, title: "Race Pace Tempo", focus: "Tempo runs at goal marathon pace" },
      { week: 12, title: "Longest Run", focus: "Final and longest long run" },
      { week: 13, title: "Sharpening", focus: "Shorter, faster reps with recovery" },
      { week: 14, title: "Taper Begins", focus: "Reduced volume, legs freshening up" },
      { week: 15, title: "Taper Continues", focus: "Further reduced volume, race prep" },
      { week: 16, title: "Race Week", focus: "Full taper into race day" },
    ],
  },
  {
    id: "p11",
    title: "General S&C",
    category: "Strength & Conditioning",
    duration: 12,
    shortDescription: "Learn the big lifts and build a strength base from the ground up.",
    fullDescription:
      "A 12-week linear progression through squat, bench, deadlift, and press, paired with conditioning finishers — built for lifters at any stage who want a well-rounded strength base.",
    coach: {
      name: "Deshawn Walker",
      initials: "DW",
      title: "Strength & Conditioning Coach",
      bio: "Teaches barbell fundamentals with an emphasis on technique before load.",
    },
    enrolledCount: 1560,
    joined: true,
    currentWeek: 12,
    enrolledLevel: "Intermediate",
    weeks: [
      { week: 1, title: "Movement Screening", focus: "Assessing mobility and lift technique" },
      { week: 2, title: "Squat Focus", focus: "Building squat pattern and confidence" },
      { week: 3, title: "Bench Focus", focus: "Building bench press technique" },
      { week: 4, title: "Deadlift Focus", focus: "Building deadlift pattern and pull strength" },
      { week: 5, title: "Press Focus", focus: "Overhead press technique and shoulder stability" },
      { week: 6, title: "Volume Block I", focus: "Higher rep ranges across all lifts" },
      { week: 7, title: "Volume Block II", focus: "Continued volume accumulation" },
      { week: 8, title: "Intensity Block I", focus: "Heavier loads, lower reps" },
      { week: 9, title: "Intensity Block II", focus: "Approaching working maxes" },
      { week: 10, title: "Conditioning Push", focus: "Metabolic finishers layered in" },
      { week: 11, title: "Peak Week", focus: "Heaviest lifts of the block" },
      { week: 12, title: "Deload & Test", focus: "Recovery week and new max testing" },
    ],
  },
  {
    id: "p12",
    title: "Bodybuilding",
    category: "Strength & Conditioning",
    duration: 12,
    shortDescription: "Build muscle and size with a structured hypertrophy-focused split.",
    fullDescription:
      "A 12-week bodybuilding block split across push, pull, and leg days, emphasizing progressive overload and mind-muscle connection to maximize muscle growth.",
    coach: {
      name: "Jonas B.",
      initials: "JB",
      title: "Bodybuilding & Hypertrophy Coach",
      bio: "Coaches lifters of all backgrounds through structured hypertrophy training for long-term muscle growth.",
    },
    enrolledCount: 1024,
    joined: false,
    currentWeek: 0,
    weeks: [
      { week: 1, title: "Foundations & Baseline", focus: "Establishing starting weights and technique" },
      { week: 2, title: "Push Volume I", focus: "Chest, shoulders, and triceps hypertrophy work" },
      { week: 3, title: "Pull Volume I", focus: "Back and biceps hypertrophy work" },
      { week: 4, title: "Leg Volume I", focus: "Quad and hamstring hypertrophy work" },
      { week: 5, title: "Push Volume II", focus: "Increasing push day volume" },
      { week: 6, title: "Pull Volume II", focus: "Increasing pull day volume" },
      { week: 7, title: "Leg Volume II", focus: "Increasing leg day volume" },
      { week: 8, title: "Intensity Block I", focus: "Heavier loads, lower reps" },
      { week: 9, title: "Intensity Block II", focus: "Continued intensity progression" },
      { week: 10, title: "Peak Volume", focus: "Highest weekly training volume" },
      { week: 11, title: "Deload", focus: "Reduced volume, active recovery" },
      { week: 12, title: "Retest & Measure", focus: "Strength retest and progress check" },
    ],
  },
  {
    id: "p13",
    title: "Glute & Lower Body Focus",
    category: "Strength & Conditioning",
    duration: 12,
    shortDescription: "Build strength, shape, and stability through the glutes and lower body.",
    fullDescription:
      "A 12-week lower-body-focused block combining hip hinge patterning, unilateral strength work, and progressive volume to build the glutes, hamstrings, and quads.",
    coach: {
      name: "Priya Shah",
      initials: "PS",
      title: "Lower Body Strength Coach",
      bio: "Specializes in glute and lower body programming, blending strength work with joint-friendly volume.",
    },
    enrolledCount: 1287,
    joined: false,
    currentWeek: 0,
    weeks: [
      { week: 1, title: "Foundations & Assessment", focus: "Movement screening and glute activation basics" },
      { week: 2, title: "Activation Volume I", focus: "Glute activation and hip hinge patterning" },
      { week: 3, title: "Posterior Chain Base", focus: "Building hamstring and glute strength" },
      { week: 4, title: "Quad & Glute Balance", focus: "Balancing quad and posterior chain work" },
      { week: 5, title: "Unilateral Focus I", focus: "Single-leg strength and stability" },
      { week: 6, title: "Volume Block I", focus: "Higher rep glute and hamstring work" },
      { week: 7, title: "Unilateral Focus II", focus: "Progressing single-leg loading" },
      { week: 8, title: "Volume Block II", focus: "Continued volume accumulation" },
      { week: 9, title: "Intensity Block I", focus: "Heavier compound lower body lifts" },
      { week: 10, title: "Intensity Block II", focus: "Continued intensity progression" },
      { week: 11, title: "Peak Week", focus: "Heaviest lower body lifts of the block" },
      { week: 12, title: "Deload & Retest", focus: "Recovery week and strength retest" },
    ],
  },
];

export function getProgram(id) {
  return programs.find((p) => p.id === id);
}

// "not-enrolled" | "enrolled" | "completed"
export function getEnrollmentStatus(program) {
  if (!program.joined) return "not-enrolled";
  if (program.currentWeek >= program.duration) return "completed";
  return "enrolled";
}
